In [8]:
library(tidyverse)
library(pheatmap)
library(data.table)

reverse_complement <- function(dna_seq) {
  complement <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  nucleotides <- unlist(strsplit(dna_seq, ""))
  complement_nucleotides <- complement[nucleotides]
  reverse_complement_seq <- paste(rev(complement_nucleotides), collapse = "")
  return(reverse_complement_seq)
}

twist_barcodes <- read_csv("/mnt/dawnccle2/melange/data/guide_library/20230130_twist_library_v3.csv") %>%
  mutate(barcodeRevcomp = sapply(barcode, reverse_complement))
all_events <- read_csv("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_all_samples_PSI_count_table_major_events.csv")

######## Look at rmats stats ########
combined_psi <- read_tsv("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/MUT_PSI_combined_output_indiv.tsv") %>%
  filter(ExonID %in% all_events$index_offset)
calculate_ratio <- function(I, S) {
  I_values <- as.numeric(unlist(strsplit(I, ",")))
  S_values <- as.numeric(unlist(strsplit(S, ",")))
  ratio <- I_values / (I_values + S_values)
  return(paste(round(ratio,3), collapse = ","))
}

calculate_average <- function(PSI){
  PSI_values <- as.numeric(unlist(strsplit(PSI, ",")))
  average <- mean(PSI_values)
  return(round(average, 3))
}

calculate_average_count_sum <- function(I, S){
  I_values <- as.numeric(unlist(strsplit(I, ",")))
  S_values <- as.numeric(unlist(strsplit(S, ",")))
  total_sum <- I_values + S_values
  average_count_sum <- mean(total_sum)
  return(round(average_count_sum, 0))
}

# Apply the function to the data frame
combined_psi <- combined_psi %>%
  mutate(
    PSI1 = mapply(calculate_ratio, I1, S1),
    PSI2 = mapply(calculate_ratio, I2, S2)
  ) %>% 
  mutate(
    PSI1_average = mapply(calculate_average, PSI1),
    PSI2_average = mapply(calculate_average, PSI2)
  ) %>%
  mutate(PSI_diff = PSI2_average - PSI1_average) %>% 
  mutate(
    count_sum_average1 = mapply(calculate_average_count_sum, I1, S1),
    count_sum_average2 = mapply(calculate_average_count_sum, I2, S2)
  ) %>% mutate(PSI_ratio = PSI2_average / PSI1_average) %>% 
  mutate(PSI_reverse_ratio = (1-PSI2_average)/(1-PSI1_average))

wanted_pairs <- c(
#'MUT2_CH3-1_A1_CH3-1_A2',
'MUT_CH3-1_A1_FUBP1_B12',
'MUT_CH3-1_A1_FUBP1_C5',
'MUT_CH3-1_A1_RBM10_C8',
'MUT_CH3-1_A1_RBM10_G4',
'MUT_CH3-1_A1_RBM5_A2',
'MUT_CH3-1_A1_RBM5_A3',
'MUT_CH3-1_A1_ZRSR2_F8',
'MUT_CH3-1_A1_ZRSR2_G9',
'MUT_CH3-1_A2_FUBP1_B12',
'MUT_CH3-1_A2_FUBP1_C5',
'MUT_CH3-1_A2_RBM10_C8',
'MUT_CH3-1_A2_RBM10_G4',
'MUT_CH3-1_A2_RBM5_A2',
'MUT_CH3-1_A2_RBM5_A3',
'MUT_CH3-1_A2_ZRSR2_F8',
'MUT_CH3-1_A2_ZRSR2_G9',
'MUT_K562WT_K562K700E',
'MUT_MUT-plx317_U2AF1_WT_MUT-plx317_U2AF1_Q157A',
'MUT_MUT-plx317_U2AF1_WT_MUT-plx-LacZ',
'MUT_MUT-sgCh3-1_MUT-sgRBM10',
'MUT_MUT-sgCh3-1_MUT-sgRBM5',
'MUT_MUT-sgCh3-1_MUT-sgRUBP1',
'MUT_splicelib_sgCh3_splicelib_ZRSR2',
'MUT_splicelib_U2AF1_WT_splicelib_U2AF1_S34F')

same_pairs <- c(
'MUT_CH3-1_A1_CH3-1_A2',
'MUT_FUBP1_B12_FUBP1_C5',
'MUT_RBM10_C8_RBM10_G4',
'MUT_RBM5_A2_RBM5_A3',
'MUT_ZRSR2_F8_ZRSR2_G9')

Rows: 46372 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): ID, barcode, upstreamIntronSeq, skippedExonSeq, downstreamIntronSeq...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2366344 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): index, mode, offset, sample, condition, index_offset
dbl (2): included_count, skipped_count

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 12763 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (6): ExonID, I1, S1, I2, S2, Folder
dbl (4): I_len, S_len, PValue, FDR

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [9]:

# Get sequences in folders MUT2_CH3-1_A1
all_ch3_a1 <- combined_psi %>% filter(grepl("MUT_CH3-1_A1", Folder)) 
chr3_a1_seq_count <- all_ch3_a1 %>% 
group_by(ExonID) %>% 
summarise(count = n()) %>% 
arrange(desc(count))

seq_to_exclude_a1 <- chr3_a1_seq_count %>% 
filter(count >=4) %>% 
pull(ExonID)

# Also exclude sequences in MUT2_CH3-1_A2
all_ch3_a2 <- combined_psi %>% filter(grepl("MUT_CH3-1_A2", Folder)) 
chr3_a2_seq_count <- all_ch3_a2 %>% 
group_by(ExonID) %>% 
summarise(count = n()) %>% 
arrange(desc(count))

seq_to_exclude_a2 <- chr3_a2_seq_count %>% 
filter(count >=4) %>% 
pull(ExonID)

# Also look at diff between A1 and A2
control_de <- combined_psi %>% 
filter(Folder == "MUT2_CH3-1_A1_CH3-1_A2") %>% 
filter(count_sum_average1 >30) %>% 
filter(count_sum_average2 > 30) %>% 
mutate(log2_PSI_ratio = log2(PSI_ratio), log2_PSI_reverse_ratio = log2(PSI_reverse_ratio)) %>% 
  separate(ExonID, sep = "__", into =c("index", "offset"), remove = FALSE) %>%
  separate(offset, into = c("skipped_exon_start", "skipped_exon_end", "downstream_exon_start"), sep = ":", remove = FALSE) %>%
  filter(abs(as.integer(skipped_exon_start)) != 1 & abs(as.integer(skipped_exon_end)) != 1) 

seq_to_exclude_control <- control_de %>% 
pull(ExonID) %>% 
unique()

all_seq_to_exclude <- c(seq_to_exclude_a1, seq_to_exclude_a2, seq_to_exclude_control)

combined_psi_filtered <- combined_psi %>% 
  filter(!ExonID %in% all_seq_to_exclude) %>% 
  # filter(Folder %in% wanted_pairs) %>%
  filter(count_sum_average1 >30) %>% 
  filter(count_sum_average2 > 30) %>% 
  mutate(log2_PSI_ratio = log2(PSI_ratio), log2_PSI_reverse_ratio = log2(PSI_reverse_ratio)) %>% 
  separate(ExonID, sep = "__", into =c("index", "offset"), remove = FALSE) %>%
  separate(offset, into = c("skipped_exon_start", "skipped_exon_end", "downstream_exon_start"), sep = ":", remove = FALSE) %>%
  filter(abs(as.integer(skipped_exon_start)) != 1 & abs(as.integer(skipped_exon_end)) != 1) 

######## Process and Save the Individual Sequences as Fasta ######
# Define a function to process and save sequences
process_and_save <- function(df, name) {
  # Define file paths
  upstream_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", name, "_upstreamIntronSeq_adj.fasta")
  skipped_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", name, "_skippedExonSeq_adj.fasta")
  downstream_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", name, "_downstreamIntronSeq_adj.fasta")
  
  # Write upstream intron sequences
  fileConn <- file(upstream_fasta, "w")
  apply(df, 1, function(row) {
    cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["upstreamIntronSeq_adj"], "\n"), file = fileConn)
  })
  close(fileConn)
  
  # Write skipped exon sequences
  fileConn <- file(skipped_fasta, "w")
  apply(df, 1, function(row) {
    cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["skippedExonSeq_adj"], "\n"), file = fileConn)
  })
  close(fileConn)
  
  # Write downstream intron sequences
  fileConn <- file(downstream_fasta, "w")
  apply(df, 1, function(row) {
    cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["downstreamIntronSeq_adj"], "\n"), file = fileConn)
  })
  close(fileConn)
  
  # Save CSV file
  csv_path <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_", name, "_seq.csv")
  write_csv(df, csv_path)
  
  # Message to indicate completion
  cat("FASTA and CSV files saved for:", name, "\n")
}

# Process and save each dataset
unique_folders <- unique(combined_psi_filtered$Folder)

# Create a list of datasets for all unique folders
datasets <- list()
for (folder in unique_folders) {
   # folder_name <- gsub("MUT2_", "", folder)  # Remove the MUT2_ prefix if present
  datasets[[folder]] <- combined_psi_filtered %>% filter(Folder == folder)
}

# Print the number of datasets to be processed
cat("Processing", length(datasets), "unique datasets\n")

for (name in names(datasets)) {
  df <- datasets[[name]] %>%
    left_join(twist_barcodes, by = c("index" = "ID")) %>%
    mutate(
      upstream_offset = as.integer(skipped_exon_start),
      downstream_offset = as.integer(skipped_exon_end),
      const_offset = as.integer(downstream_exon_start),
      upstreamIntron_len = nchar(upstreamIntronSeq),
      downstreamIntron_len = nchar(downstreamIntronSeq),
      skippedExon_len = nchar(skippedExonSeq),
      upstreamIntron_len_adj = upstreamIntron_len + upstream_offset,
      downstreamIntron_len_adj = downstreamIntron_len - downstream_offset,
      skippedExon_len_adj = skippedExon_len - upstream_offset + downstream_offset,
      upstreamIntronSeq_adj = substr(librarySequence, 1, upstreamIntron_len_adj),
      skippedExonSeq_adj = substr(librarySequence, upstreamIntron_len_adj + 1, upstreamIntron_len_adj + skippedExon_len_adj),
      downstreamIntronSeq_adj = substr(librarySequence, upstreamIntron_len_adj + skippedExon_len_adj + 1, upstreamIntron_len_adj + skippedExon_len_adj + downstreamIntron_len_adj)
    )
  
  process_and_save(df, name)
}

cat("Processing complete for all datasets.\n")

# Make the "background sequence" file 
upstream_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", "background_upstreamIntronSeq_adj.fasta")
skipped_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", "background_skippedExonSeq_adj.fasta")
downstream_fasta <- paste0("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/", "background_downstreamIntronSeq_adj.fasta")

# Write upstream intron sequences
fileConn <- file(upstream_fasta, "w")
apply(twist_barcodes, 1, function(row) {
  cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["upstreamIntronSeq"], "\n"), file = fileConn)
})
close(fileConn)

# Write skipped exon sequences
fileConn <- file(skipped_fasta, "w")
apply(twist_barcodes, 1, function(row) {
  cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["skippedExonSeq"], "\n"), file = fileConn)
})
close(fileConn)

# Write downstream intron sequences
fileConn <- file(downstream_fasta, "w")
apply(twist_barcodes, 1, function(row) {
  cat(paste0(">", paste0(row["barcode"], "_", row["offset"]), "\n", row["downstreamIntronSeq"], "\n"), file = fileConn)
})
close(fileConn)

Processing 28 unique datasets
FASTA and CSV files saved for: MUT_CH3-1_A1_CH3-1_A2
FASTA and CSV files saved for: MUT_CH3-1_A1_FUBP1_B12
FASTA and CSV files saved for: MUT_CH3-1_A1_FUBP1_C5
FASTA and CSV files saved for: MUT_CH3-1_A1_RBM10_C8
FASTA and CSV files saved for: MUT_CH3-1_A1_RBM10_G4
FASTA and CSV files saved for: MUT_CH3-1_A1_RBM5_A2
FASTA and CSV files saved for: MUT_CH3-1_A1_RBM5_A3
FASTA and CSV files saved for: MUT_CH3-1_A1_ZRSR2_F8
FASTA and CSV files saved for: MUT_CH3-1_A1_ZRSR2_G9
FASTA and CSV files saved for: MUT_CH3-1_A2_FUBP1_B12
FASTA and CSV files saved for: MUT_CH3-1_A2_FUBP1_C5
FASTA and CSV files saved for: MUT_CH3-1_A2_RBM10_C8
FASTA and CSV files saved for: MUT_CH3-1_A2_RBM10_G4
FASTA and CSV files saved for: MUT_CH3-1_A2_RBM5_A2
FASTA and CSV files saved for: MUT_CH3-1_A2_RBM5_A3
FASTA and CSV files saved for: MUT_CH3-1_A2_ZRSR2_F8
FASTA and CSV files saved for: MUT_CH3-1_A2_ZRSR2_G9
FASTA and CSV files saved for: MUT_FUBP1_B12_FUBP1_C5
FASTA and CSV files saved for: MUT_K562WT_K562K700E
FASTA and CSV files saved for: MUT_MUT-plx317_U2AF1_WT_MUT-plx317_U2AF1_Q157A
FASTA and CSV files saved for: MUT_MUT-sgCh3-1_MUT-sgRBM10
FASTA and CSV files saved for: MUT_MUT-sgCh3-1_MUT-sgRBM5
FASTA and CSV files saved for: MUT_MUT-sgCh3-1_MUT-sgRUBP1
FASTA and CSV files saved for: MUT_RBM10_C8_RBM10_G4
FASTA and CSV files saved for: MUT_RBM5_A2_RBM5_A3
FASTA and CSV files saved for: MUT_splicelib_sgCh3_splicelib_ZRSR2
FASTA and CSV files saved for: MUT_splicelib_U2AF1_WT_splicelib_U2AF1_S34F
FASTA and CSV files saved for: MUT_ZRSR2_F8_ZRSR2_G9
Processing complete for all datasets.

NULL

NULL

NULL

In [10]:
# Plot the volcano plot
# save the plot
p1 <- ggplot(combined_psi_filtered, aes(log2(PSI_ratio), -log10(FDR))) + 
  geom_point() + 
  facet_wrap(~Folder, nrow = 4) +
  theme_classic() +
  ggtitle("PSI ratio")
ggsave("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_volcano_plot_PSI_ratio.png", p1, width = 20, height = 20)

# Plot PSI_reverse_ratio
p2 <- ggplot(combined_psi_filtered, aes(log2(PSI_reverse_ratio), -log10(FDR))) + 
  geom_point() + 
  facet_wrap(~Folder, nrow = 4) +
  theme_classic() +
  ggtitle("PSI reverse ratio")
ggsave("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_volcano_plot_PSI_reverse_ratio.png", p2, width = 20, height = 20)

# Also plot the PSI_dff
p3 <- ggplot(combined_psi_filtered, aes(PSI_diff, -log10(FDR))) + 
  geom_point() + 
  facet_wrap(~Folder, nrow = 4) +
  theme_classic() +
  ggtitle("PSI diff")
ggsave("/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_volcano_plot_PSI_diff.png", p3, width = 20, height = 20)

In [11]:
# blacklist
blacklist_seqs <- c("MUT_CH3-1_A1_CH3-1_A2",
"MUT_FUBP1_B12_FUBP1_C5",
"MUT_RBM10_C8_RBM10_G4",
"MUT_RBM5_A2_RBM5_A3",
"MUT_ZRSR2_F8_ZRSR2_G9")

# Across all samples, get log2(PSI_ratio) > 2
high_ratio <- combined_psi_filtered %>% 
filter(!Folder %in% blacklist_seqs) %>% 
filter(log2_PSI_ratio >= 3 | log2_PSI_reverse_ratio >= 3) %>% 
filter(abs(PSI_diff) >= 0.3) %>% 
arrange(desc(pmax(log2_PSI_ratio, log2_PSI_reverse_ratio))) %>%
    left_join(twist_barcodes, by = c("index" = "ID")) %>%
    mutate(
      upstream_offset = as.integer(skipped_exon_start),
      downstream_offset = as.integer(skipped_exon_end),
      const_offset = as.integer(downstream_exon_start),
      upstreamIntron_len = nchar(upstreamIntronSeq),
      downstreamIntron_len = nchar(downstreamIntronSeq),
      skippedExon_len = nchar(skippedExonSeq),
      upstreamIntron_len_adj = upstreamIntron_len + upstream_offset,
      downstreamIntron_len_adj = downstreamIntron_len - downstream_offset,
      skippedExon_len_adj = skippedExon_len - upstream_offset + downstream_offset,
      upstreamIntronSeq_adj = substr(librarySequence, 1, upstreamIntron_len_adj),
      skippedExonSeq_adj = substr(librarySequence, upstreamIntron_len_adj + 1, upstreamIntron_len_adj + skippedExon_len_adj),
      downstreamIntronSeq_adj = substr(librarySequence, upstreamIntron_len_adj + skippedExon_len_adj + 1, upstreamIntron_len_adj + skippedExon_len_adj + downstreamIntron_len_adj)
    )

write_csv(high_ratio, "/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_high_ratio_PSI.csv")


# Save a separate file for not multiple of 3 for skippedExon_len_adj
high_ratio_not_multiple_of_3 <- high_ratio %>%
  filter(skippedExon_len_adj %% 3 != 0)

write_csv(high_ratio_not_multiple_of_3, "/mnt/dawnccle2/processed_data/reprocess_250221/pairadise_indiv_PSI/seq_output/MUT_high_ratio_PSI_not_multiple_of_3.csv")


nrow(high_ratio)
# Get how many in each folder
high_ratio %>% 
group_by(Folder) %>% 
summarise(count = n()) %>% 
arrange(desc(count)) %>% 
head(20)


high_ratio %>% 
    group_by(ExonID) %>% 
    summarise(n = n(),
    samples = paste(Folder, collapse = ","),
    log_fold_change = paste(round(log2_PSI_reverse_ratio,3), collapse = ",")) %>% 
    arrange(desc(n)) %>% 
    head(20)
# Get how many unique sequences
length(unique(high_ratio$ExonID))

[1] 126

   Folder                                         count
1  MUT_K562WT_K562K700E                           36
2  MUT_CH3-1_A1_ZRSR2_F8                          16
3  MUT_CH3-1_A1_ZRSR2_G9                          13
4  MUT_CH3-1_A1_FUBP1_B12                         12
5  MUT_CH3-1_A1_RBM5_A2                            9
6  MUT_CH3-1_A1_FUBP1_C5                           7
7  MUT_CH3-1_A2_RBM10_G4                           5
8  MUT_CH3-1_A1_RBM5_A3                            4
9  MUT_CH3-1_A2_FUBP1_B12                          4
10 MUT_MUT-sgCh3-1_MUT-sgRBM5                      4
11 MUT_CH3-1_A2_RBM5_A3                            3
12 MUT_splicelib_sgCh3_splicelib_ZRSR2             3
13 MUT_CH3-1_A2_FUBP1_C5                           2
14 MUT_CH3-1_A2_RBM10_C8                           2
15 MUT_splicelib_U2AF1_WT_splicelib_U2AF1_S34F     2
16 MUT_CH3-1_A1_RBM10_G4                           1
17 MUT_CH3-1_A2_RBM5_A2                            1
18 MUT_CH3-1_A2_ZRSR2_G9                           1
19 MUT_MUT-plx317_U2AF1_WT_MUT-plx317_U2AF1_Q157A  1

   ExonID
1  ENSG00000164615.6;CAMLG;chr5-134743986-134744052-134738496-134741523-134750758-134751377__0:0:0
2  ENSG00000075914.13;EXOSC7;chr3-44989549-44989644-44976243-44976334-44997086-44997252__0:0:0
3  ENSG00000082996.20;RNF13;chr3-149921133-149921227-149911977-149912083-149960055-149960136__0:0:0
4  ENSG00000105696.9;TMEM59L;chr19-18616999-18617102-18615974-18616127-18618154-18618222__0:0:0
5  ENSG00000111863.13;ADTRP;chr6-11770030-11770084-11768248-11768383-11778606-11778803__0:0:0
6  ENSG00000129116.19;PALLD;chr4-168896548-168896599-168894440-168894677-168898492-168898714__0:0:0
7  ENSG00000143194.13;MAEL;chr1-166991377-166991477-166989736-166989829-166992685-166992841__0:0:0
8  ENSG00000144036.16;EXOC6B;chr2-72514633-72514680-72513131-72513252-72515042-72515126__0:0:0
9  ENSG00000183077.15;AFMID;chr17-78190969-78191060-78187316-78187433-78197134-78197560__0:0:0
10 ENSG00000186439.14;TRDN;chr6-123274640-123274670-123273336-123273363-123278317-123278347__0:0:0
11 ENSG00000198898.14;CAPZA2;chr7-116906262-116906342-116904176-116904383-116910212-116910231__0:0:0
12 ENSG00000205209.8;SCGB2B2;chr19-34632007-34632051-34594502-34596594-34675629-34677159__0:0:0
13 ENSG00000214655.11;ZSWIM8;chr10-73789716-73789824-73789095-73789190-73789955-73790037__0:0:0
14 ENSG00000240303.8;ACAD11;chr3-132579491-132579558-132578548-132579056-132603228-132603327__0:0:0
15 ENSG00000008382.16;MPND;chr19-4354044-4354129-4352896-4353029-4354323-4354420__0:0:0
16 ENSG00000030066.13;NUP160;chr11-47797778-47797884-47792011-47792946-47797977-47798074__0:0:0
17 ENSG00000039123.16;MTREX;chr5-55353167-55353269-55341680-55341771-55358572-55358698__0:0:0
18 ENSG00000048471.14;SNX29;chr16-12078832-12078915-12069056-12069132-12126632-12126696__0:0:0
19 ENSG00000056277.16;ZNF280C;chrX-130205116-130205153-130202706-130204992-130205296-130205415__0:0:0
20 ENSG00000059573.9;ALDH18A1;chr10-95632958-95633049-95628367-95628492-95633490-95633649__0:0:0
   n samples
1  3 MUT_CH3-1_A1_RBM5_A2,MUT_CH3-1_A1_ZRSR2_F8,MUT_CH3-1_A1_ZRSR2_G9
2  2 MUT_CH3-1_A2_FUBP1_B12,MUT_CH3-1_A1_FUBP1_B12
3  2 MUT_CH3-1_A1_RBM5_A3,MUT_CH3-1_A2_RBM5_A3
4  2 MUT_CH3-1_A1_RBM10_G4,MUT_CH3-1_A2_RBM10_G4
5  2 MUT_CH3-1_A1_RBM5_A3,MUT_CH3-1_A1_ZRSR2_F8
6  2 MUT_CH3-1_A2_RBM10_G4,MUT_CH3-1_A2_RBM10_C8
7  2 MUT_CH3-1_A1_FUBP1_B12,MUT_CH3-1_A1_RBM5_A2
8  2 MUT_CH3-1_A1_ZRSR2_F8,MUT_CH3-1_A1_ZRSR2_G9
9  2 MUT_CH3-1_A1_FUBP1_C5,MUT_CH3-1_A2_FUBP1_C5
10 2 MUT_CH3-1_A1_ZRSR2_F8,MUT_CH3-1_A1_ZRSR2_G9
11 2 MUT_CH3-1_A1_ZRSR2_F8,MUT_CH3-1_A1_ZRSR2_G9
12 2 MUT_CH3-1_A1_ZRSR2_F8,MUT_CH3-1_A1_RBM5_A2
13 2 MUT_CH3-1_A1_FUBP1_B12,MUT_CH3-1_A2_FUBP1_B12
14 2 MUT_CH3-1_A2_RBM5_A3,MUT_CH3-1_A1_RBM5_A3
15 1 MUT_K562WT_K562K700E
16 1 MUT_K562WT_K562K700E
17 1 MUT_K562WT_K562K700E
18 1 MUT_CH3-1_A2_ZRSR2_G9
19 1 MUT_CH3-1_A1_FUBP1_B12
20 1 MUT_CH3-1_A1_RBM5_A2
   log_fold_change
1  Inf,Inf,Inf
2  3.958,3.61
3  Inf,Inf
4  -0.65,-0.65
5  6.511,6.049
6  -0.567,-0.558
7  3.628,3.483
8  3.931,3.796
9  Inf,Inf
10 6.581,6.476
11 Inf,Inf
12 3.548,3.51
13 4.065,3.337
14 3.704,3.611
15 3.816
16 3.538
17 5.982
18 3.337
19 3.644
20 3.978

[1] 111