In [28]:
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import random

from sklearn.model_selection import train_test_split
from torch.utils.data import Subset

# plot correlation
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import pearsonr, spearmanr

# Set publication-quality style
plt.rcParams.update({
    'font.family': 'Arial',
    'font.size': 12,
    'axes.linewidth': 1.5,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 12,
    'axes.titlesize': 16,
    'pdf.fonttype': 42
})

# Set random seed for reproducibility
seed = 0
random.seed(seed)
np.random.seed(seed)    
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

GX = pd.read_csv('~/lab_projects/splicing/for_kai/V4_data_with_offset_major_event_only/241126_gene_expression_all.csv')
# GX = pd.read_csv('~/lab_projects/splicing/for_kai/V4_data_with_offset_major_event_only/241126_gene_expression_RBP_only.csv')
PSI = pd.read_csv('~/lab_projects/splicing/for_kai/V4_data_with_offset_major_event_only/250407_measurement_ratio.csv')
Barcode = pd.read_csv('~/lab_projects/splicing/for_kai/V4_data_with_offset_major_event_only/250407_twist_barcodes_with_splice_site_annotation.csv')

In [29]:
GX_dict = GX.groupby("condition").apply(
    lambda x: np.array(x.drop(columns=["Unnamed: 0", "condition"]).values.flatten().tolist())
).to_dict()

/tmp/ipykernel_15265/3826946481.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  GX_dict = GX.groupby("condition").apply(

In [30]:
# make index as the barcode
Barcode = Barcode.set_index("index_offset")
Barcode = Barcode.drop(columns=["Unnamed: 0"])
Barcode

,padded_sequence,exon_intron_map,is_splice_acceptor,is_splice_donor
index_offset,,,,
ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539__0:0:0,CTTCGACACCGAGCTCGATATGATCGAAGTATTTATTACCATAAAG...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252__0:0:0,GCTTCGACACCGAGCTCGTCGAGAACTTATTTGACCTGAAACCAAA...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000000003.15;TSPAN6;chrX-100635177-100635252-100633930-100634029-100635557-100635746__0:0:0,GCTTCGACACCGAGCTCGAGACGACCATTATTTTTTCTTTGACTCC...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000000419.14;DPM1;chr20-50945736-50945762-50942030-50942126-50945846-50945861__0:0:0,TGAGATTGAATCCAGGAAATGAAGCTTCGACACCGAGCTCGTTAGC...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000000419.14;DPM1;chr20-50948628-50948662-50945736-50945923-50955185-50955285__0:0:0,CTTCGACACCGAGCTCGGTGCAACTATATTTCTATTAAAGTGAGTA...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
...,...,...,...,...
ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__0:0:0,CTTCGACACCGAGCTCGACCCAACATGCCCAAACACTGTTCTTTTT...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000288710.1;RP11-386G11.12;chr12-49022279-49022353-49022042-49022151-49022589-49022875__0:0:0,CTTCGACACCGAGCTCGACTGCCTGAGTCTCCTACCTGATCCCACA...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000288717.1;RP11-852E15.4;chr3-46000912-46000955-45995957-45996035-46001083-46001283__0:0:0,GCTTCGACACCGAGCTCGAGATGAAGGCAAGGTTAGGGGTATCCGT...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389__0:0:0,GCTTCGACACCGAGCTCGACTTAAATTGAAAAAGAAATCCAGCTTC...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...
ENSG00000288723.1;RP11-553N16.6;chr1-241742058-241742106-241728734-241728834-241765061-241765184__0:0:0,CTTCGACACCGAGCTCGGTTCATATTCCAGCCGTCATGCTTATGCC...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...,0000000000000000000000000000000000000000000000...

In [31]:
# make index as the barcode
PSI = PSI.set_index("index_offset")
PSI = PSI.drop(columns=["Unnamed: 0"])
PSI

,769P,786O,8MGBA,A172,A375,ACHN,CAL120,COGN278,COLO783,DAOY,...,SF126,SKNAS,SNU398,SNU423,SNU449,SNUC4,T47D,TOV21G,U251MG,VMRCRCZ
index_offset,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539__0:0:0,5.855052,6.955650,4.786596,5.066832,4.343257,5.347252,6.247928,5.172890,9.967226,8.377934,...,9.967226,4.703436,5.544321,3.755662,9.967226,9.967226,6.139551,9.967226,9.967226,9.967226
ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252__0:0:0,4.160823,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,...,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226
ENSG00000000003.15;TSPAN6;chrX-100635177-100635252-100633930-100634029-100635557-100635746__0:0:0,NaN,1.069751,-0.060542,-0.147135,-0.503730,1.844684,NaN,1.994607,9.967226,2.121991,...,-0.095157,0.997839,1.779734,NaN,-1.286800,1.089583,-0.147135,0.678072,0.617465,0.828326
ENSG00000000419.14;DPM1;chr20-50945736-50945762-50942030-50942126-50945846-50945861__0:0:0,1.252026,1.712718,3.996940,2.492914,-0.233995,2.835563,1.672780,4.786596,0.158698,1.149682,...,2.632603,4.829909,1.633412,4.160823,2.093702,2.248800,3.801190,1.163165,0.794913,1.641242
ENSG00000000419.14;DPM1;chr20-50948628-50948662-50945736-50945923-50955185-50955285__0:0:0,NaN,NaN,0.280483,NaN,-3.321928,-1.581126,NaN,NaN,NaN,NaN,...,NaN,-1.116179,NaN,NaN,NaN,NaN,-1.736966,-2.248800,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__0:0:0,-0.684164,-0.135578,-0.474069,-2.756957,-2.731449,0.118249,-0.714717,0.503730,0.991361,0.292127,...,-0.895303,-0.819826,0.014413,-1.203909,-2.862496,-0.794913,-2.822237,-2.822237,-0.971986,-0.129800
ENSG00000288710.1;RP11-386G11.12;chr12-49022279-49022353-49022042-49022151-49022589-49022875__0:0:0,-0.539463,0.895303,0.095157,-0.391524,-1.238212,1.116179,-0.828326,1.192349,-0.072078,0.907996,...,1.328998,-0.060542,1.581126,-0.379787,-1.422312,0.462233,-0.901645,-0.491853,0.690262,0.456320
ENSG00000288717.1;RP11-852E15.4;chr3-46000912-46000955-45995957-45996035-46001083-46001283__0:0:0,-0.309611,0.545434,0.426815,1.036911,-1.541097,0.521577,-0.228193,1.176697,0.170265,2.681408,...,0.665905,-0.158698,0.303781,-0.112475,-0.474069,0.770115,0.257222,0.794913,0.344648,2.142811
ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389__0:0:0,0.708594,3.824428,1.328998,0.037475,1.844684,3.689610,1.300808,2.706269,1.939508,2.131497,...,1.688686,2.160257,1.939508,1.321928,2.141044,1.836238,-0.757757,2.131497,2.504197,2.341037
ENSG00000288723.1;RP11-553N16.6;chr1-241742058-241742106-241728734-241728834-241765061-241765184__0:0:0,NaN,5.475733,6.955650,6.038553,9.967226,9.967226,9.967226,9.967226,9.967226,9.967226,...,5.066832,9.967226,3.712890,6.038553,9.967226,9.967226,8.964341,6.955650,9.967226,4.663464

In [32]:
num_na = PSI.isna().sum().sum()
num_non_na = PSI.size - num_na

print(f"NA: {num_na}")
print(f"~NA: {num_non_na}")

NA: 119406
~NA: 1982178

In [33]:
def onehot_encode_sequences(sequences):
    """
    One-hot encodes a list of DNA sequences.

    Args:
        sequences (list of str): A list of DNA sequences, each containing characters 'A', 'G', 'C', 'T'.

    Returns:
        np.ndarray: A 3D numpy array where each sequence is one-hot encoded along the last axis.
    """
    # Define a mapping for bases
    base_mapping = {'A': 0, 'G': 1, 'C': 2, 'T': 3, 'N': 4}
    n_sequences = len(sequences)
    sequence_length = len(sequences[0]) if sequences else 0
    
    # Initialize the one-hot encoded array
    onehot_array = np.zeros((n_sequences, sequence_length, 4), dtype=int)
    
    for i, seq in enumerate(sequences):
        for j, base in enumerate(seq):
            if base in base_mapping:  # Ensure valid base
                onehot_array[i, j, base_mapping[base]] = 1
                
    return onehot_array

Barcode_onehot = onehot_encode_sequences(list(Barcode['padded_sequence'].values))
# Barcode_onehot = np.concatenate((Barcode_onehot, twist_array), axis=-1)
print(Barcode_onehot.shape)
Barcode_dict = dict(zip(Barcode.index, Barcode_onehot))

(43783, 250, 4)

In [34]:
class PSIDataset(Dataset):
    def __init__(self, PSI_df, Barcode_dict, GX_dict):
        self.samples = []
    
        for barcode in PSI_df.index:
            if barcode not in Barcode_dict:
                continue  
            
            barcode_array = Barcode_dict[barcode] 
            
            for celltype in PSI_df.columns:
                if celltype not in GX_dict:
                    continue 
                
                gx_array = GX_dict[celltype] 
                psi_value = PSI_df.loc[barcode, celltype]
                
                if not np.isnan(psi_value):
                    self.samples.append((celltype, barcode, barcode_array, gx_array, psi_value))
    
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, idx):
        celltype, barcode, barcode_array, gx_array, psi_value = self.samples[idx]
        return celltype, barcode, barcode_array, gx_array, psi_value
    
def split_dataset_by_barcode(dataset, test_size=0.2, random_state=42):
    """
    Split the dataset into train and test subsets based on barcode.
    Params:
    - dataset: PSIDataset
    - test_size: ratio
    - random_state
    
    Return:
    - train_dataset
    - test_dataset
    """
    # Extract all barcodes
    barcodes = np.array([sample[1] for sample in dataset.samples])
    
    # Get unique barcodes and split
    unique_barcodes = np.unique(barcodes)
    
    train_barcodes, test_barcodes = train_test_split(
        unique_barcodes, test_size=test_size, random_state=random_state
    )
    
    print(f"Train barcodes: {train_barcodes[:5]}")
    print(f"Test barcodes: {test_barcodes[:5]}") 
    
    train_barcodes_set = set(train_barcodes)
    test_barcodes_set = set(test_barcodes)
    
    # Get indices for train and test
    train_indices = np.where(np.isin(barcodes, list(train_barcodes_set)))[0]
    test_indices = np.where(np.isin(barcodes, list(test_barcodes_set)))[0]
    print(f"Train indices: {len(train_indices)}, Test indices: {len(test_indices)}")
    
    # Construct Subsets
    train_dataset = Subset(dataset, train_indices)
    test_dataset = Subset(dataset, test_indices)
    
    return train_dataset, test_dataset

def split_dataset_by_celltype(dataset, test_size=0.2, random_state=42):
    """
    Split the dataset into train and test subsets based on celltype.
    Params:
    - dataset: PSIDataset
    - test_size: ratio
    - random_state
    
    Return:
    - train_dataset
    - test_dataset
    """
    celltypes = np.array([sample[0] for sample in dataset.samples])
    
    unique_celltypes = np.unique(celltypes)
    train_celltypes, test_celltypes = train_test_split(
        unique_celltypes, test_size=test_size, random_state=random_state
    )
    
    print(f"Train celltypes: {len(train_celltypes)}, Test celltypes: {len(test_celltypes)}")
    
    train_indices = [i for i, celltype in enumerate(celltypes) if celltype in train_celltypes]
    test_indices = [i for i, celltype in enumerate(celltypes) if celltype in test_celltypes]
    
    train_dataset = Subset(dataset, train_indices)
    test_dataset = Subset(dataset, test_indices)
    
    assert len(train_dataset) == len(train_indices), "Train dataset size mismatch!"
    assert len(test_dataset) == len(test_indices), "Test dataset size mismatch!"
    
    return train_dataset, test_dataset

def split_dataset_random(dataset, test_size=0.2, random_state=42):

    dataset_size = len(dataset)
    
    indices = list(range(dataset_size))
    
    train_indices, test_indices = train_test_split(
        indices, test_size=test_size, random_state=random_state
    )
    
    train_dataset = Subset(dataset, train_indices)
    test_dataset = Subset(dataset, test_indices)
    
    return train_dataset, test_dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

lr = 1e-4
epochs = 5
batch_size = 1024

dataset = PSIDataset(PSI, Barcode_dict, GX_dict)
dataset_size = len(dataset)
print(f"Total samples: {dataset_size}")

# # train_dataset, test_dataset = split_dataset_random(dataset, test_size=0.2, random_state=42)
# train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=42)

# # train_dataset, test_dataset = split_dataset_by_celltype(dataset, test_size=0.2, random_state=42)
# print(f"Train samples: {len(train_dataset)}, Test samples: {len(test_dataset)}")
# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=8)
# test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)

Total samples: 1828278

## Convolutional Neural Network

In [35]:
class GexFullyConnected(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(in_features=19221, out_features=1024)
        self.fc2 = nn.Linear(in_features=1024, out_features=256)
        self.fc3 = nn.Linear(in_features=256, out_features=128)
        self.BN1 = nn.BatchNorm1d(1024)
        self.BN2 = nn.BatchNorm1d(256) 
        self.dropout = nn.Dropout(0.2)     

    def forward(self, x):
        x = F.relu(self.BN1(self.fc1(x)))
        x = F.relu(self.BN2(self.fc2(x)))
        x = F.relu(self.fc3(x))
        return x

class ResNetCNN(nn.Module):
    def __init__(self, channels, dropout=0.2):
        super().__init__() 
        
        self.conv1_5 =  nn.Conv1d(channels, channels, kernel_size=5, padding=2)  
        self.conv1_11 = nn.Conv1d(channels, channels, kernel_size=11, padding=5)
        self.conv1_21 = nn.Conv1d(channels, channels, kernel_size=21, padding=10)

        self.batchnorm1 = nn.BatchNorm1d(channels * 3) 
        self.dropout = nn.Dropout(dropout)
        self.conv_merge = nn.Conv1d(channels * 3, channels, kernel_size=1)

        self.conv2 = nn.Conv1d(channels, channels, kernel_size=5, padding=2)
        self.batchnorm2 = nn.BatchNorm1d(channels)

    def forward(self, x):
        residual = x 
        x1 = self.conv1_5(x)
        x2 = self.conv1_11(x)
        x3 = self.conv1_21(x)

        x = torch.cat([x1, x2, x3], dim=1) 

        x = self.dropout(F.relu(self.batchnorm1(x)))
        x = self.conv_merge(x) 
        x = self.dropout(F.relu(self.batchnorm2(self.conv2(x))))
        
        x += residual  
        return x

class SequenceCNN(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.dropout = nn.Dropout(0.2)
        
        self.conv1 = nn.Conv1d(in_channels=4, out_channels=128, kernel_size=1, padding='same')
        self.batchnorm1 = nn.BatchNorm1d(128)
    
        self.resnetCNN1 = nn.Sequential(
            ResNetCNN(128),
            ResNetCNN(128),
            ResNetCNN(128),
        )
        
        self.maxpool = nn.MaxPool1d(kernel_size=2)
        
        self.conv2 = nn.Conv1d(in_channels=128, out_channels=64, kernel_size=1, padding='same')
        self.batchnorm2 = nn.BatchNorm1d(64)
        
        self.resnetCNN2 = nn.Sequential(
            ResNetCNN(64),
            ResNetCNN(64),
            ResNetCNN(64),
        )
        
        self.conv3 = nn.Conv1d(in_channels=64, out_channels=16, kernel_size=1, padding='same')
        self.batchnorm3 = nn.BatchNorm1d(16)
        
        self.resnetCNN3 = nn.Sequential(
            ResNetCNN(16),
            ResNetCNN(16),
            ResNetCNN(16),
        )

        self.conv4 = nn.Conv1d(in_channels=128, out_channels=16, kernel_size=1, padding='same')
        self.maxpool8 = nn.MaxPool1d(kernel_size=8)
        
        # Linear layers
        self.fc1 = nn.Linear(in_features=496, out_features=128)
        
    def forward(self, x):
        x = self.dropout(F.relu(self.batchnorm1(self.conv1(x))))
        residual = x
        x_residual = x
        x = self.resnetCNN1(x)
        x += residual
        x = self.maxpool(x)
        
        x = self.dropout(F.relu(self.batchnorm2(self.conv2(x))))
        residual = x
        x = self.resnetCNN2(x)
        x += residual
        x = self.maxpool(x)
        
        x = self.dropout(F.relu(self.batchnorm3(self.conv3(x))))
        residual = x
        x = self.resnetCNN3(x)
        x += residual
        x = self.maxpool(x)
        
        x_residual = self.conv4(x_residual)
        x_residual = self.maxpool8(x_residual)
        x = x + x_residual
        
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        
        return x

class Predictor_gene_barcode(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.Barcode_model = SequenceCNN()
        self.GX_model = GexFullyConnected()

        self.fc1 = nn.Linear(in_features=128, out_features=64)
        self.bn1 = nn.BatchNorm1d(64)
        self.fc2 = nn.Linear(in_features=64, out_features=1)
        
        self.dropout = nn.Dropout(0.2)
    
    def forward(self, barcode, gx, condition):
        
        z_barcode = self.Barcode_model(barcode)
        
        z_gx = self.GX_model(gx)
        x = z_barcode + z_gx + condition
        x = self.dropout(F.leaky_relu(self.bn1(self.fc1(x))))
        x = self.fc2(x)
        
        return x
    
class Predictor_barcode(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.Barcode_model = SequenceCNN()

        self.fc1 = nn.Linear(in_features=128, out_features=64)
        self.bn1 = nn.BatchNorm1d(64)
        self.fc2 = nn.Linear(in_features=64, out_features=1)
        
        self.dropout = nn.Dropout(0.2)
    
    def forward(self, barcode):
        
        x = self.Barcode_model(barcode)
        x = self.dropout(F.leaky_relu(self.bn1(self.fc1(x))))
        x = self.fc2(x)
        
        return x

## Evaluation for model_gene_barcode

In [36]:
import os
output_dir = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/"
seed_set = range(10)
all_correlations = []

for seed in seed_set:
    random.seed(seed)
    np.random.seed(seed)    
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Create train/test split using current seed
    train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=seed)
    print(f"Seed {seed} - Train samples: {len(train_dataset)}, Test samples: {len(test_dataset)}")

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=8)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)

    model_barcode = Predictor_barcode()
    model_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_PSI_no_mut_5epoch_seed{seed}.pth"))
    model_barcode.eval()
    model_barcode = model_barcode.to(device)

    MSELoss = nn.MSELoss()
    optimizer = torch.optim.Adam(model_barcode.parameters(), lr=lr)

    model_gene_barcode = Predictor_gene_barcode()
    model_gene_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_gene_PSI_no_mut_5epoch_seed{seed}.pth"))
    model_gene_barcode.eval()
    model_gene_barcode = model_gene_barcode.to(device)
    
    predict_psi = []
    real_psi = []
    psi_residuals = []
    celltypes = []
    barcode_names = []
    
    with torch.no_grad():
        psi_loss = 0
        recon_loss = 0
        for i, (celltype, barcode_name, barcode, gx, psi) in enumerate(test_loader):
            barcode = barcode.to(device).float()
            barcode = barcode.permute(0, 2, 1)
            gx = gx.to(device).float()
            psi = psi.to(device).float()
        
            condition = model_barcode.Barcode_model(barcode)
            psi_pretrain = model_barcode(barcode)
        
            psi_residual = model_gene_barcode(barcode, gx, condition)
            psi_loss += MSELoss(psi_residual.squeeze(), psi-psi_pretrain.squeeze()).item()
            
            predict_psi.extend(psi_residual.squeeze().cpu().numpy()+psi_pretrain.squeeze().cpu().numpy())
            psi_residuals.extend(psi_residual.squeeze().cpu().numpy())
            real_psi.extend(psi.cpu().numpy())
            celltypes.extend(celltype)
            barcode_names.extend(barcode_name)

    pearson_correlation, _ = pearsonr(real_psi, predict_psi)
    spearman_correlation, _ = spearmanr(real_psi, predict_psi)
    all_correlations.append((pearson_correlation, spearman_correlation))
    
    print(f"\nSeed {seed}:")
    print(f"Pearson Correlation: {pearson_correlation:.4f}")
    print(f"Spearman Correlation: {spearman_correlation:.4f}")

    # Save predictions for this seed
    psi_results_df = pd.DataFrame({
        'Real_PSI': real_psi,
        'Predicted_PSI': predict_psi,
        'PSI_Residuals': psi_residuals,
        'Celltype': celltypes,
        'Barcode': barcode_names
    })
    psi_results_df.to_csv(os.path.join(output_dir, f'psi_predictions_barcode_gene_seed{seed}.csv'), index=False)
    print(f"Saved PSI predictions to {os.path.join(output_dir, f'psi_predictions_barcode_gene_seed{seed}.csv')}")

    # Create and save scatter plot for this seed
    plt.figure(figsize=(8, 8), dpi=300)
    plt.scatter(real_psi, predict_psi, alpha=0.5, s=5, c='#336695', edgecolors='none', marker='o', rasterized=True)
    plt.plot([-10, 10], [-10, 10], 'k--', alpha=0.5, zorder=0)
    plt.xlabel("Observed PSI", fontsize=14, fontweight='bold')
    plt.ylabel("Predicted PSI", fontsize=14, fontweight='bold')
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    plt.xlim(-10, 10)
    plt.ylim(min(predict_psi), max(predict_psi))
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['left'].set_linewidth(1.5)
    plt.gca().spines['bottom'].set_linewidth(1.5)
    plt.title(f"Prediction Performance on Wild-type Data (Seed {seed})", fontsize=16, fontweight='bold', pad=20)
    stats_text = f"Pearson r = {pearson_correlation:.3f}\nSpearman ρ = {spearman_correlation:.3f}"
    plt.text(0.05, 0.95, stats_text,
             transform=plt.gca().transAxes,
             bbox=dict(facecolor='white', edgecolor='none', alpha=0.7),
             fontsize=12,
             verticalalignment='top')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'predicted_vs_real_psi_gene_barcode_seed{seed}.pdf'), 
                bbox_inches='tight', 
                dpi=300)
    plt.close()

# After all seeds are processed, create summary statistics and plots
pearson_values = [c[0] for c in all_correlations]
spearman_values = [c[1] for c in all_correlations]

# Save correlation values to CSV
correlation_df = pd.DataFrame({
    'Pearson': pearson_values,
    'Spearman': spearman_values
})
correlation_df.to_csv(os.path.join(output_dir, 'correlation_values_model_barcode_gene.csv'), index=False)

# Calculate means and stds
pearson_mean = np.mean(pearson_values)
pearson_std = np.std(pearson_values)
spearman_mean = np.mean(spearman_values)
spearman_std = np.std(spearman_values)

# Create and save box plot
plt.figure(figsize=(8, 6))
box_data = [pearson_values, spearman_values]
plt.boxplot(box_data, labels=['Pearson', 'Spearman'])
plt.ylabel('Correlation')
plt.title('Correlation Scores Across Seeds')
x_positions = [1, 2]
for i, data in enumerate([pearson_values, spearman_values]):
    plt.scatter([x_positions[i]] * len(data), data, alpha=0.5, color='black')
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
print(f"\nAverage across all seeds:")
print(f"Pearson Correlation: {pearson_mean:.4f} ± {pearson_std:.4f}")
print(f"Spearman Correlation: {spearman_mean:.4f} ± {spearman_std:.4f}")
plt.savefig(os.path.join(output_dir, 'correlation_boxplot.pdf'), 
            bbox_inches='tight', 
            dpi=300)
plt.close()

Train barcodes: ['ENSG00000184156.17;KCNQ3;chr8-132134325-132134388-132132179-132132264-132137884-132138016__0:0:0'
 'ENSG00000105613.10;MAST1;chr19-12858361-12858441-12852327-12852395-12858530-12858739__0:0:0'
 'ENSG00000171109.19;MFN1;chr3-179365117-179365225-179364296-179364405-179367438-179367498__0:0:0'
 'ENSG00000203321.2;CARNMT1-AS1;chr9-74991620-74991674-74991164-74991285-74995997-74996293__0:0:0'
 'ENSG00000104823.9;ECH1;chr19-38817315-38817364-38817064-38817129-38831077-38831166__0:0:0']
Test barcodes: ['ENSG00000133106.15;EPSTI1;chr13-42963254-42963338-42953947-42954021-42969093-42969177__0:0:0'
 'ENSG00000183671.12;GPR1;chr2-206203893-206203948-206176565-206177275-206213306-206213371__0:0:0'
 'ENSG00000145741.16;BTF3;chr5-73504346-73504403-73502487-73503117-73505191-73505435__0:0:0'
 'ENSG00000124596.17;OARD1;chr6-41075266-41075349-41071595-41071675-41097712-41097787__0:0:0'
 'ENSG00000096063.16;SRPK1;chr6-35920467-35920528-35890894-35891013-35921043-35921072__0:0:0']
Train indices: 1463578, Test indices: 364700
Seed 0 - Train samples: 1463578, Test samples: 364700

Seed 0:
Pearson Correlation: 0.7299
Spearman Correlation: 0.7369
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed0.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000138152.10;BTBD16;chr10-122297767-122297837-122291079-122291194-122307188-122307308__0:0:0'
 'ENSG00000123411.15;IKZF4;chr12-56018125-56018177-56007668-56007734-56025053-56025158__0:0:0'
 'ENSG00000146263.12;MMS22L;chr6-97246627-97246690-97233860-97233980-97267871-97268002__0:0:0'
 'ENSG00000122126.17;OCRL;chrX-129567253-129567363-129565771-129565883-129569263-129569399__0:0:0'
 'ENSG00000137845.15;ADAM10;chr15-58643885-58643978-58640776-58640960-58646054-58646204__0:0:0']
Test barcodes: ['ENSG00000066923.18;STAG3;chr7-100182722-100182839-100182089-100182192-100189444-100189596__0:0:0'
 'ENSG00000100003.18;SEC14L2;chr22-30406341-30406385-30399642-30399718-30407094-30407154__0:0:0'
 'ENSG00000100344.11;PNPLA3;chr22-43928823-43928889-43926934-43927167-43932877-43933087__0:0:0'
 'ENSG00000183431.12;SF3A3;chr1-37978987-37979055-37976883-37976953-37979464-37979533__0:0:0'
 'ENSG00000021826.17;CPS1;chr2-210668185-210668284-210663122-210663197-210674901-210674961__0:0:0']
Train indices: 1462250, Test indices: 366028
Seed 1 - Train samples: 1462250, Test samples: 366028

Seed 1:
Pearson Correlation: 0.7146
Spearman Correlation: 0.7195
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed1.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000223458.2;LMO7DN-IT1;chr13-75878714-75878794-75876885-75876965-75879703-75879782__0:0:0'
 'ENSG00000164692.18;COL1A2;chr7-94409722-94409821-94409563-94409608-94410241-94410295__0:0:0'
 'ENSG00000100033.17;PRODH;chr22-18921341-18921423-18919705-18919798-18925050-18925200__0:0:0'
 'ENSG00000172995.17;ARPP21;chr3-35708968-35709070-35706973-35707082-35715438-35715476__0:0:0'
 'ENSG00000145700.10;ANKRD31;chr5-75112512-75112600-75107520-75107617-75116565-75116681__0:0:0']
Test barcodes: ['ENSG00000164134.13;NAA15;chr4-139354025-139354098-139351504-139351611-139359742-139359857__0:0:0'
 'ENSG00000136878.14;USP20;chr9-129856306-129856360-129852539-129852636-129858049-129858112__0:0:0'
 'ENSG00000177830.18;CHID1;chr11-899339-899401-893426-893519-900003-900110__0:0:0'
 'ENSG00000262879.6;RP11-156P1.3;chr17-47007839-47007884-46998699-46998817-47021581-47021721__0:0:0'
 'ENSG00000149403.13;GRIK4;chr11-120898531-120898639-120875138-120875243-120905289-120905493__0:0:0']
Train indices: 1462336, Test indices: 365942
Seed 2 - Train samples: 1462336, Test samples: 365942

Seed 2:
Pearson Correlation: 0.7356
Spearman Correlation: 0.7438
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed2.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000060718.22;COL11A1;chr1-102997079-102997124-102995988-102996042-102998309-102998363__0:0:0'
 'ENSG00000049541.11;RFC2;chr7-74249011-74249118-74243145-74243246-74249738-74249780__0:0:0'
 'ENSG00000155324.10;GRAMD2B;chr5-126472237-126472304-126465425-126465545-126473264-126473368__0:0:0'
 'ENSG00000166888.12;STAT6;chr12-57102828-57102921-57102289-57102496-57104725-57104813__0:0:0'
 'ENSG00000064419.14;TNPO3;chr7-128967279-128967392-128957222-128957315-128970147-128970315__0:0:0']
Test barcodes: ['ENSG00000100888.15;CHD8;chr14-21399980-21400070-21399601-21399705-21400150-21400307__0:0:0'
 'ENSG00000206503.13;HLA-A;chr6-29945233-29945281-29944499-29945091-29945450-29945870__0:0:0'
 'ENSG00000110944.9;IL23A;chr12-56339425-56339524-56338883-56339206-56339942-56340305__0:0:0'
 'ENSG00000166200.15;COPS2;chr15-49144226-49144304-49137347-49137458-49155524-49155590__0:0:0'
 'ENSG00000276409.5;CCL14;chr17-35984337-35984452-35983287-35983888-35986570-35986729__0:0:0']
Train indices: 1462613, Test indices: 365665
Seed 3 - Train samples: 1462613, Test samples: 365665

Seed 3:
Pearson Correlation: 0.7395
Spearman Correlation: 0.7448
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed3.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000143367.16;TUFT1;chr1-151574910-151575005-151574269-151574398-151578720-151578826__0:0:0'
 'ENSG00000104973.19;MED25;chr19-49835533-49835605-49832883-49835177-49835726-49835945__0:0:0'
 'ENSG00000084636.18;COL16A1;chr1-31683333-31683369-31683193-31683247-31683949-31684003__0:0:0'
 'ENSG00000197969.14;VPS13A;chr9-77225925-77225988-77221184-77221356-77226465-77226598__0:0:0'
 'ENSG00000260192.3;LINC02240;chr5-125440598-125440695-125325351-125325447-125498775-125498956__0:0:0']
Test barcodes: ['ENSG00000110375.3;UPK2;chr11-118951203-118951265-118925163-118925291-118956882-118957014__0:0:0'
 'ENSG00000275832.5;ARHGAP23;chr17-38490461-38490551-38490101-38490175-38491406-38491532__0:0:0'
 'ENSG00000159140.21;SON;chr21-33567156-33567267-33559586-33559775-33568970-33569087__0:0:0'
 'ENSG00000133055.9;MYBPH;chr1-203168626-203168675-203167810-203168091-203168905-203169091__0:0:0'
 'ENSG00000213064.10;SFT2D2;chr1-168236711-168236770-168235100-168235182-168239130-168239160__0:0:0']
Train indices: 1462573, Test indices: 365705
Seed 4 - Train samples: 1462573, Test samples: 365705

Seed 4:
Pearson Correlation: 0.7288
Spearman Correlation: 0.7319
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed4.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000106070.20;GRB10;chr7-50612740-50612839-50590062-50593098-50616209-50616347__0:0:0'
 'ENSG00000132256.20;TRIM5;chr11-5667688-5667711-5665980-5666081-5678203-5678434__0:0:0'
 'ENSG00000160633.13;SAFB;chr19-5626404-5626489-5623034-5623394-5641593-5641658__0:0:0'
 'ENSG00000123243.15;ITIH5;chr10-7609419-7609494-7585900-7586069-7615981-7616098__0:0:0'
 'ENSG00000166946.14;CCNDBP1;chr15-43185819-43185879-43185327-43185607-43189198-43189280__0:0:0']
Test barcodes: ['ENSG00000274391.5;TPTE;chr21-10577459-10577520-10570484-10570549-10578516-10578605__0:0:0'
 'ENSG00000185864.17;NPIPB4;chr16-21839104-21839140-21834581-21837744-21839249-21839310__0:0:0'
 'ENSG00000050438.17;SLC4A8;chr12-51493703-51493772-51489699-51489951-51494944-51495118__0:0:0'
 'ENSG00000143537.14;ADAM15;chr1-155052670-155052777-155051285-155051465-155053416-155053493__0:0:0'
 'ENSG00000280987.4;MATR3;chr5-139322462-139322506-139321897-139322029-139322597-139322967__0:0:0']
Train indices: 1462916, Test indices: 365362
Seed 5 - Train samples: 1462916, Test samples: 365362

Seed 5:
Pearson Correlation: 0.7329
Spearman Correlation: 0.7368
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed5.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000164308.17;ERAP2;chr5-96900120-96900189-96896731-96896863-96901505-96901681__0:0:0'
 'ENSG00000009335.18;UBE3C;chr7-157174918-157175034-157170303-157170450-157178689-157178847__0:0:0'
 'ENSG00000132849.21;PATJ;chr1-62017855-62017947-61990167-61990364-62037976-62038049__0:0:0'
 'ENSG00000167992.13;VWCE;chr11-61265121-61265212-61264955-61265038-61267461-61267544__0:0:0'
 'ENSG00000180071.20;ANKRD18A;chr9-38588550-38588663-38586182-38586312-38593759-38593909__0:0:0']
Test barcodes: ['ENSG00000101596.16;SMCHD1;chr18-2726451-2726524-2724898-2724995-2728456-2728596__0:0:0'
 'ENSG00000136448.13;NMT1;chr17-45096193-45096285-45086507-45086652-45098381-45098552__0:0:0'
 'ENSG00000115009.13;CCL20;chr2-227815456-227815568-227813841-227813987-227816306-227816384__0:0:0'
 'ENSG00000162946.23;DISC1;chr1-231701954-231702024-231693825-231694805-231749925-231750076__0:0:0'
 'ENSG00000168542.16;COL3A1;chr2-188989395-188989449-188988080-188988134-188990306-188990360__0:0:0']
Train indices: 1462538, Test indices: 365740
Seed 6 - Train samples: 1462538, Test samples: 365740

Seed 6:
Pearson Correlation: 0.7341
Spearman Correlation: 0.7404
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed6.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000156500.16;PABIR3;chrX-134847885-134847971-134847382-134847475-134849166-134849228__0:0:0'
 'ENSG00000113851.15;CRBN;chr3-3154746-3154831-3153423-3153488-3156218-3156281__0:0:0'
 'ENSG00000121578.13;B4GALT4;chr3-119218711-119218772-119216238-119216344-119224057-119224245__0:0:0'
 'ENSG00000163359.17;COL6A3;chr2-237396726-237396762-237381295-237381499-237414278-237414327__-85:0:0'
 'ENSG00000031003.10;FAM13B;chr5-137952627-137952709-137948954-137949184-137953335-137953465__0:0:0']
Test barcodes: ['ENSG00000058600.16;POLR3E;chr16-22313657-22313727-22309427-22309510-22314078-22314128__-38:0:0'
 'ENSG00000156374.16;PCGF6;chr10-103314185-103314272-103302795-103303961-103326533-103326632__0:0:0'
 'ENSG00000153363.13;LINC00467;chr1-211391615-211391697-211382735-211382925-211391826-211391976__0:0:0'
 'ENSG00000007866.22;TEAD3;chr6-35478274-35478324-35477310-35477372-35478433-35478571__0:0:0'
 'ENSG00000155115.7;GTF3C6;chr6-110960413-110960477-110959171-110959252-110962391-110962505__0:0:0']
Train indices: 1462452, Test indices: 365826
Seed 7 - Train samples: 1462452, Test samples: 365826

Seed 7:
Pearson Correlation: 0.7279
Spearman Correlation: 0.7348
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed7.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000134690.11;CDCA8;chr1-37706977-37707064-37703251-37703347-37708321-37709713__0:0:0'
 'ENSG00000100578.18;KIAA0586;chr14-58512521-58512627-58508554-58508709-58540070-58540136__0:0:0'
 'ENSG00000102001.13;CACNA1F;chrX-49214158-49214269-49213818-49213902-49215085-49215244__0:0:0'
 'ENSG00000167306.20;MYO5B;chr18-49990438-49990520-49980443-49980553-49992287-49992431__0:0:0'
 'ENSG00000198677.12;TTC37;chr5-95506933-95506992-95503813-95503938-95513570-95513645__-19:0:0']
Test barcodes: ['ENSG00000141030.13;COPS3;chr17-17261599-17261692-17260373-17260474-17261965-17262106__0:0:0'
 'ENSG00000065413.20;ANKRD44;chr2-197187022-197187106-197147026-197147105-197310577-197310646__0:0:0'
 'ENSG00000001617.12;SEMA3F;chr3-50174051-50174114-50173792-50173953-50174230-50174350__0:0:0'
 'ENSG00000148187.18;MRRF;chr9-122291748-122291840-122270807-122271075-122322539-122323092__0:0:0'
 'ENSG00000131966.14;ACTR10;chr14-58207935-58208018-58202854-58202927-58208998-58209107__0:0:0']
Train indices: 1462170, Test indices: 366108
Seed 8 - Train samples: 1462170, Test samples: 366108

Seed 8:
Pearson Correlation: 0.7279
Spearman Correlation: 0.7329
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed8.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000068971.14;PPP2R5B;chr11-64928065-64928158-64927733-64927903-64928294-64928425__0:0:0'
 'ENSG00000123240.17;OPTN;chr10-13116266-13116340-13112452-13112635-13118887-13118980__0:-57:0'
 'ENSG00000272281.6;TPTE2P2;chr13-52229325-52229431-52227004-52227096-52253744-52253833__0:0:0'
 'ENSG00000047849.22;MAP4;chr3-47867245-47867338-47857430-47857512-47869213-47869327__0:0:0'
 'ENSG00000144867.13;SRPRB;chr3-133807745-133807823-133806552-133806703-133811116-133811199__0:0:0']
Test barcodes: ['ENSG00000105879.12;CBLL1;chr7-107753894-107753978-107753410-107753511-107758142-107758571__0:0:0'
 'ENSG00000140943.17;MBTPS1;chr16-84091731-84091848-84090874-84090942-84093710-84093821__0:0:0'
 'ENSG00000129460.16;NGDN;chr14-23470905-23470977-23469743-23470101-23475170-23475308__0:0:0'
 'ENSG00000205426.10;KRT81;chr12-52288360-52288456-52287983-52288148-52289214-52289275__0:0:0'
 'ENSG00000136811.16;ODF2;chr9-128492425-128492536-128487889-128488025-128492700-128492805__0:0:0']
Train indices: 1462672, Test indices: 365606
Seed 9 - Train samples: 1462672, Test samples: 365606

Seed 9:
Pearson Correlation: 0.7305
Spearman Correlation: 0.7369
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed9.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
/tmp/ipykernel_15265/186953194.py:126: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.
  plt.boxplot(box_data, labels=['Pearson', 'Spearman'])
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Average across all seeds:
Pearson Correlation: 0.7302 ± 0.0063
Spearman Correlation: 0.7359 ± 0.0068

# Evaluation for model with high variance data for finetune

In [37]:
import os
output_dir = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/"
seed_set = range(10)
all_correlations = []

for seed in seed_set:
    random.seed(seed)
    np.random.seed(seed)    
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Create train/test split using current seed
    train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=seed)
    print(f"Seed {seed} - Train samples: {len(train_dataset)}, Test samples: {len(test_dataset)}")

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=8)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)

    model_barcode = Predictor_barcode()
    model_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_PSI_no_mut_5epoch_seed{seed}.pth"))
    model_barcode.eval()
    model_barcode = model_barcode.to(device)

    MSELoss = nn.MSELoss()
    optimizer = torch.optim.Adam(model_barcode.parameters(), lr=lr)

    model_gene_barcode = Predictor_gene_barcode()
    model_gene_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_gene_PSI_no_mut_5epoch_high_var_only_seed{seed}.pth"))
    model_gene_barcode.eval()
    model_gene_barcode = model_gene_barcode.to(device)
    
    predict_psi = []
    real_psi = []
    psi_residuals = []
    celltypes = []
    barcode_names = []
    
    with torch.no_grad():
        psi_loss = 0
        recon_loss = 0
        for i, (celltype, barcode_name, barcode, gx, psi) in enumerate(test_loader):
            barcode = barcode.to(device).float()
            barcode = barcode.permute(0, 2, 1)
            gx = gx.to(device).float()
            psi = psi.to(device).float()
        
            condition = model_barcode.Barcode_model(barcode)
            psi_pretrain = model_barcode(barcode)
        
            psi_residual = model_gene_barcode(barcode, gx, condition)
            psi_loss += MSELoss(psi_residual.squeeze(), psi-psi_pretrain.squeeze()).item()
            
            predict_psi.extend(psi_residual.squeeze().cpu().numpy()+psi_pretrain.squeeze().cpu().numpy())
            psi_residuals.extend(psi_residual.squeeze().cpu().numpy())
            real_psi.extend(psi.cpu().numpy())
            celltypes.extend(celltype)
            barcode_names.extend(barcode_name)

    pearson_correlation, _ = pearsonr(real_psi, predict_psi)
    spearman_correlation, _ = spearmanr(real_psi, predict_psi)
    all_correlations.append((pearson_correlation, spearman_correlation))
    
    print(f"\nSeed {seed}:")
    print(f"Pearson Correlation: {pearson_correlation:.4f}")
    print(f"Spearman Correlation: {spearman_correlation:.4f}")

    # Save predictions for this seed
    psi_results_df = pd.DataFrame({
        'Real_PSI': real_psi,
        'Predicted_PSI': predict_psi,
        'PSI_Residuals': psi_residuals,
        'Celltype': celltypes,
        'Barcode': barcode_names
    })
    psi_results_df.to_csv(os.path.join(output_dir, f'psi_predictions_barcode_gene_high_var_only_seed{seed}.csv'), index=False)
    print(f"Saved PSI predictions to {os.path.join(output_dir, f'psi_predictions_barcode_gene_high_var_only_seed{seed}.csv')}")

    # Create and save scatter plot for this seed
    plt.figure(figsize=(8, 8), dpi=300)
    plt.scatter(real_psi, predict_psi, alpha=0.5, s=5, c='#336695', edgecolors='none', marker='o', rasterized=True)
    plt.plot([-10, 10], [-10, 10], 'k--', alpha=0.5, zorder=0)
    plt.xlabel("Observed PSI", fontsize=14, fontweight='bold')
    plt.ylabel("Predicted PSI", fontsize=14, fontweight='bold')
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    plt.xlim(-10, 10)
    plt.ylim(min(predict_psi), max(predict_psi))
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['left'].set_linewidth(1.5)
    plt.gca().spines['bottom'].set_linewidth(1.5)
    plt.title(f"Prediction Performance on Wild-type Data (Seed {seed})", fontsize=16, fontweight='bold', pad=20)
    stats_text = f"Pearson r = {pearson_correlation:.3f}\nSpearman ρ = {spearman_correlation:.3f}"
    plt.text(0.05, 0.95, stats_text,
             transform=plt.gca().transAxes,
             bbox=dict(facecolor='white', edgecolor='none', alpha=0.7),
             fontsize=12,
             verticalalignment='top')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'predicted_vs_real_psi_gene_barcode_high_var_only_seed{seed}.pdf'), 
                bbox_inches='tight', 
                dpi=300)
    plt.close()

# After all seeds are processed, create summary statistics and plots
pearson_values = [c[0] for c in all_correlations]
spearman_values = [c[1] for c in all_correlations]

# Save correlation values to CSV
correlation_df = pd.DataFrame({
    'Pearson': pearson_values,
    'Spearman': spearman_values
})
correlation_df.to_csv(os.path.join(output_dir, 'correlation_values_model_barcode_gene_high_var_only.csv'), index=False)

# Calculate means and stds
pearson_mean = np.mean(pearson_values)
pearson_std = np.std(pearson_values)
spearman_mean = np.mean(spearman_values)
spearman_std = np.std(spearman_values)

# Create and save box plot
plt.figure(figsize=(8, 6))
box_data = [pearson_values, spearman_values]
plt.boxplot(box_data, labels=['Pearson', 'Spearman'])
plt.ylabel('Correlation')
plt.title('Correlation Scores Across Seeds')
x_positions = [1, 2]
for i, data in enumerate([pearson_values, spearman_values]):
    plt.scatter([x_positions[i]] * len(data), data, alpha=0.5, color='black')
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
print(f"\nAverage across all seeds:")
print(f"Pearson Correlation: {pearson_mean:.4f} ± {pearson_std:.4f}")
print(f"Spearman Correlation: {spearman_mean:.4f} ± {spearman_std:.4f}")
plt.savefig(os.path.join(output_dir, 'correlation_boxplot_high_var_only.pdf'), 
            bbox_inches='tight', 
            dpi=300)
plt.close()

Train barcodes: ['ENSG00000184156.17;KCNQ3;chr8-132134325-132134388-132132179-132132264-132137884-132138016__0:0:0'
 'ENSG00000105613.10;MAST1;chr19-12858361-12858441-12852327-12852395-12858530-12858739__0:0:0'
 'ENSG00000171109.19;MFN1;chr3-179365117-179365225-179364296-179364405-179367438-179367498__0:0:0'
 'ENSG00000203321.2;CARNMT1-AS1;chr9-74991620-74991674-74991164-74991285-74995997-74996293__0:0:0'
 'ENSG00000104823.9;ECH1;chr19-38817315-38817364-38817064-38817129-38831077-38831166__0:0:0']
Test barcodes: ['ENSG00000133106.15;EPSTI1;chr13-42963254-42963338-42953947-42954021-42969093-42969177__0:0:0'
 'ENSG00000183671.12;GPR1;chr2-206203893-206203948-206176565-206177275-206213306-206213371__0:0:0'
 'ENSG00000145741.16;BTF3;chr5-73504346-73504403-73502487-73503117-73505191-73505435__0:0:0'
 'ENSG00000124596.17;OARD1;chr6-41075266-41075349-41071595-41071675-41097712-41097787__0:0:0'
 'ENSG00000096063.16;SRPK1;chr6-35920467-35920528-35890894-35891013-35921043-35921072__0:0:0']
Train indices: 1463578, Test indices: 364700
Seed 0 - Train samples: 1463578, Test samples: 364700

Seed 0:
Pearson Correlation: 0.7263
Spearman Correlation: 0.7335
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed0.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000138152.10;BTBD16;chr10-122297767-122297837-122291079-122291194-122307188-122307308__0:0:0'
 'ENSG00000123411.15;IKZF4;chr12-56018125-56018177-56007668-56007734-56025053-56025158__0:0:0'
 'ENSG00000146263.12;MMS22L;chr6-97246627-97246690-97233860-97233980-97267871-97268002__0:0:0'
 'ENSG00000122126.17;OCRL;chrX-129567253-129567363-129565771-129565883-129569263-129569399__0:0:0'
 'ENSG00000137845.15;ADAM10;chr15-58643885-58643978-58640776-58640960-58646054-58646204__0:0:0']
Test barcodes: ['ENSG00000066923.18;STAG3;chr7-100182722-100182839-100182089-100182192-100189444-100189596__0:0:0'
 'ENSG00000100003.18;SEC14L2;chr22-30406341-30406385-30399642-30399718-30407094-30407154__0:0:0'
 'ENSG00000100344.11;PNPLA3;chr22-43928823-43928889-43926934-43927167-43932877-43933087__0:0:0'
 'ENSG00000183431.12;SF3A3;chr1-37978987-37979055-37976883-37976953-37979464-37979533__0:0:0'
 'ENSG00000021826.17;CPS1;chr2-210668185-210668284-210663122-210663197-210674901-210674961__0:0:0']
Train indices: 1462250, Test indices: 366028
Seed 1 - Train samples: 1462250, Test samples: 366028

Seed 1:
Pearson Correlation: 0.7197
Spearman Correlation: 0.7247
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed1.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000223458.2;LMO7DN-IT1;chr13-75878714-75878794-75876885-75876965-75879703-75879782__0:0:0'
 'ENSG00000164692.18;COL1A2;chr7-94409722-94409821-94409563-94409608-94410241-94410295__0:0:0'
 'ENSG00000100033.17;PRODH;chr22-18921341-18921423-18919705-18919798-18925050-18925200__0:0:0'
 'ENSG00000172995.17;ARPP21;chr3-35708968-35709070-35706973-35707082-35715438-35715476__0:0:0'
 'ENSG00000145700.10;ANKRD31;chr5-75112512-75112600-75107520-75107617-75116565-75116681__0:0:0']
Test barcodes: ['ENSG00000164134.13;NAA15;chr4-139354025-139354098-139351504-139351611-139359742-139359857__0:0:0'
 'ENSG00000136878.14;USP20;chr9-129856306-129856360-129852539-129852636-129858049-129858112__0:0:0'
 'ENSG00000177830.18;CHID1;chr11-899339-899401-893426-893519-900003-900110__0:0:0'
 'ENSG00000262879.6;RP11-156P1.3;chr17-47007839-47007884-46998699-46998817-47021581-47021721__0:0:0'
 'ENSG00000149403.13;GRIK4;chr11-120898531-120898639-120875138-120875243-120905289-120905493__0:0:0']
Train indices: 1462336, Test indices: 365942
Seed 2 - Train samples: 1462336, Test samples: 365942

Seed 2:
Pearson Correlation: 0.7318
Spearman Correlation: 0.7397
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed2.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000060718.22;COL11A1;chr1-102997079-102997124-102995988-102996042-102998309-102998363__0:0:0'
 'ENSG00000049541.11;RFC2;chr7-74249011-74249118-74243145-74243246-74249738-74249780__0:0:0'
 'ENSG00000155324.10;GRAMD2B;chr5-126472237-126472304-126465425-126465545-126473264-126473368__0:0:0'
 'ENSG00000166888.12;STAT6;chr12-57102828-57102921-57102289-57102496-57104725-57104813__0:0:0'
 'ENSG00000064419.14;TNPO3;chr7-128967279-128967392-128957222-128957315-128970147-128970315__0:0:0']
Test barcodes: ['ENSG00000100888.15;CHD8;chr14-21399980-21400070-21399601-21399705-21400150-21400307__0:0:0'
 'ENSG00000206503.13;HLA-A;chr6-29945233-29945281-29944499-29945091-29945450-29945870__0:0:0'
 'ENSG00000110944.9;IL23A;chr12-56339425-56339524-56338883-56339206-56339942-56340305__0:0:0'
 'ENSG00000166200.15;COPS2;chr15-49144226-49144304-49137347-49137458-49155524-49155590__0:0:0'
 'ENSG00000276409.5;CCL14;chr17-35984337-35984452-35983287-35983888-35986570-35986729__0:0:0']
Train indices: 1462613, Test indices: 365665
Seed 3 - Train samples: 1462613, Test samples: 365665

Seed 3:
Pearson Correlation: 0.7284
Spearman Correlation: 0.7358
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed3.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000143367.16;TUFT1;chr1-151574910-151575005-151574269-151574398-151578720-151578826__0:0:0'
 'ENSG00000104973.19;MED25;chr19-49835533-49835605-49832883-49835177-49835726-49835945__0:0:0'
 'ENSG00000084636.18;COL16A1;chr1-31683333-31683369-31683193-31683247-31683949-31684003__0:0:0'
 'ENSG00000197969.14;VPS13A;chr9-77225925-77225988-77221184-77221356-77226465-77226598__0:0:0'
 'ENSG00000260192.3;LINC02240;chr5-125440598-125440695-125325351-125325447-125498775-125498956__0:0:0']
Test barcodes: ['ENSG00000110375.3;UPK2;chr11-118951203-118951265-118925163-118925291-118956882-118957014__0:0:0'
 'ENSG00000275832.5;ARHGAP23;chr17-38490461-38490551-38490101-38490175-38491406-38491532__0:0:0'
 'ENSG00000159140.21;SON;chr21-33567156-33567267-33559586-33559775-33568970-33569087__0:0:0'
 'ENSG00000133055.9;MYBPH;chr1-203168626-203168675-203167810-203168091-203168905-203169091__0:0:0'
 'ENSG00000213064.10;SFT2D2;chr1-168236711-168236770-168235100-168235182-168239130-168239160__0:0:0']
Train indices: 1462573, Test indices: 365705
Seed 4 - Train samples: 1462573, Test samples: 365705

Seed 4:
Pearson Correlation: 0.7236
Spearman Correlation: 0.7282
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed4.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000106070.20;GRB10;chr7-50612740-50612839-50590062-50593098-50616209-50616347__0:0:0'
 'ENSG00000132256.20;TRIM5;chr11-5667688-5667711-5665980-5666081-5678203-5678434__0:0:0'
 'ENSG00000160633.13;SAFB;chr19-5626404-5626489-5623034-5623394-5641593-5641658__0:0:0'
 'ENSG00000123243.15;ITIH5;chr10-7609419-7609494-7585900-7586069-7615981-7616098__0:0:0'
 'ENSG00000166946.14;CCNDBP1;chr15-43185819-43185879-43185327-43185607-43189198-43189280__0:0:0']
Test barcodes: ['ENSG00000274391.5;TPTE;chr21-10577459-10577520-10570484-10570549-10578516-10578605__0:0:0'
 'ENSG00000185864.17;NPIPB4;chr16-21839104-21839140-21834581-21837744-21839249-21839310__0:0:0'
 'ENSG00000050438.17;SLC4A8;chr12-51493703-51493772-51489699-51489951-51494944-51495118__0:0:0'
 'ENSG00000143537.14;ADAM15;chr1-155052670-155052777-155051285-155051465-155053416-155053493__0:0:0'
 'ENSG00000280987.4;MATR3;chr5-139322462-139322506-139321897-139322029-139322597-139322967__0:0:0']
Train indices: 1462916, Test indices: 365362
Seed 5 - Train samples: 1462916, Test samples: 365362

Seed 5:
Pearson Correlation: 0.7276
Spearman Correlation: 0.7282
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed5.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000164308.17;ERAP2;chr5-96900120-96900189-96896731-96896863-96901505-96901681__0:0:0'
 'ENSG00000009335.18;UBE3C;chr7-157174918-157175034-157170303-157170450-157178689-157178847__0:0:0'
 'ENSG00000132849.21;PATJ;chr1-62017855-62017947-61990167-61990364-62037976-62038049__0:0:0'
 'ENSG00000167992.13;VWCE;chr11-61265121-61265212-61264955-61265038-61267461-61267544__0:0:0'
 'ENSG00000180071.20;ANKRD18A;chr9-38588550-38588663-38586182-38586312-38593759-38593909__0:0:0']
Test barcodes: ['ENSG00000101596.16;SMCHD1;chr18-2726451-2726524-2724898-2724995-2728456-2728596__0:0:0'
 'ENSG00000136448.13;NMT1;chr17-45096193-45096285-45086507-45086652-45098381-45098552__0:0:0'
 'ENSG00000115009.13;CCL20;chr2-227815456-227815568-227813841-227813987-227816306-227816384__0:0:0'
 'ENSG00000162946.23;DISC1;chr1-231701954-231702024-231693825-231694805-231749925-231750076__0:0:0'
 'ENSG00000168542.16;COL3A1;chr2-188989395-188989449-188988080-188988134-188990306-188990360__0:0:0']
Train indices: 1462538, Test indices: 365740
Seed 6 - Train samples: 1462538, Test samples: 365740

Seed 6:
Pearson Correlation: 0.7357
Spearman Correlation: 0.7413
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed6.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000156500.16;PABIR3;chrX-134847885-134847971-134847382-134847475-134849166-134849228__0:0:0'
 'ENSG00000113851.15;CRBN;chr3-3154746-3154831-3153423-3153488-3156218-3156281__0:0:0'
 'ENSG00000121578.13;B4GALT4;chr3-119218711-119218772-119216238-119216344-119224057-119224245__0:0:0'
 'ENSG00000163359.17;COL6A3;chr2-237396726-237396762-237381295-237381499-237414278-237414327__-85:0:0'
 'ENSG00000031003.10;FAM13B;chr5-137952627-137952709-137948954-137949184-137953335-137953465__0:0:0']
Test barcodes: ['ENSG00000058600.16;POLR3E;chr16-22313657-22313727-22309427-22309510-22314078-22314128__-38:0:0'
 'ENSG00000156374.16;PCGF6;chr10-103314185-103314272-103302795-103303961-103326533-103326632__0:0:0'
 'ENSG00000153363.13;LINC00467;chr1-211391615-211391697-211382735-211382925-211391826-211391976__0:0:0'
 'ENSG00000007866.22;TEAD3;chr6-35478274-35478324-35477310-35477372-35478433-35478571__0:0:0'
 'ENSG00000155115.7;GTF3C6;chr6-110960413-110960477-110959171-110959252-110962391-110962505__0:0:0']
Train indices: 1462452, Test indices: 365826
Seed 7 - Train samples: 1462452, Test samples: 365826

Seed 7:
Pearson Correlation: 0.7281
Spearman Correlation: 0.7358
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed7.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000134690.11;CDCA8;chr1-37706977-37707064-37703251-37703347-37708321-37709713__0:0:0'
 'ENSG00000100578.18;KIAA0586;chr14-58512521-58512627-58508554-58508709-58540070-58540136__0:0:0'
 'ENSG00000102001.13;CACNA1F;chrX-49214158-49214269-49213818-49213902-49215085-49215244__0:0:0'
 'ENSG00000167306.20;MYO5B;chr18-49990438-49990520-49980443-49980553-49992287-49992431__0:0:0'
 'ENSG00000198677.12;TTC37;chr5-95506933-95506992-95503813-95503938-95513570-95513645__-19:0:0']
Test barcodes: ['ENSG00000141030.13;COPS3;chr17-17261599-17261692-17260373-17260474-17261965-17262106__0:0:0'
 'ENSG00000065413.20;ANKRD44;chr2-197187022-197187106-197147026-197147105-197310577-197310646__0:0:0'
 'ENSG00000001617.12;SEMA3F;chr3-50174051-50174114-50173792-50173953-50174230-50174350__0:0:0'
 'ENSG00000148187.18;MRRF;chr9-122291748-122291840-122270807-122271075-122322539-122323092__0:0:0'
 'ENSG00000131966.14;ACTR10;chr14-58207935-58208018-58202854-58202927-58208998-58209107__0:0:0']
Train indices: 1462170, Test indices: 366108
Seed 8 - Train samples: 1462170, Test samples: 366108

Seed 8:
Pearson Correlation: 0.7223
Spearman Correlation: 0.7252
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed8.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Train barcodes: ['ENSG00000068971.14;PPP2R5B;chr11-64928065-64928158-64927733-64927903-64928294-64928425__0:0:0'
 'ENSG00000123240.17;OPTN;chr10-13116266-13116340-13112452-13112635-13118887-13118980__0:-57:0'
 'ENSG00000272281.6;TPTE2P2;chr13-52229325-52229431-52227004-52227096-52253744-52253833__0:0:0'
 'ENSG00000047849.22;MAP4;chr3-47867245-47867338-47857430-47857512-47869213-47869327__0:0:0'
 'ENSG00000144867.13;SRPRB;chr3-133807745-133807823-133806552-133806703-133811116-133811199__0:0:0']
Test barcodes: ['ENSG00000105879.12;CBLL1;chr7-107753894-107753978-107753410-107753511-107758142-107758571__0:0:0'
 'ENSG00000140943.17;MBTPS1;chr16-84091731-84091848-84090874-84090942-84093710-84093821__0:0:0'
 'ENSG00000129460.16;NGDN;chr14-23470905-23470977-23469743-23470101-23475170-23475308__0:0:0'
 'ENSG00000205426.10;KRT81;chr12-52288360-52288456-52287983-52288148-52289214-52289275__0:0:0'
 'ENSG00000136811.16;ODF2;chr9-128492425-128492536-128487889-128488025-128492700-128492805__0:0:0']
Train indices: 1462672, Test indices: 365606
Seed 9 - Train samples: 1462672, Test samples: 365606

Seed 9:
Pearson Correlation: 0.7269
Spearman Correlation: 0.7354
Saved PSI predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_high_var_only_seed9.csv

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
/tmp/ipykernel_15265/1984624931.py:126: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.
  plt.boxplot(box_data, labels=['Pearson', 'Spearman'])
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Average across all seeds:
Pearson Correlation: 0.7270 ± 0.0044
Spearman Correlation: 0.7328 ± 0.0056

# For RBP_only

In [38]:
# import os
# output_dir = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/"
# seed_set = range(10)
# all_correlations = []

# for seed in seed_set:
#     random.seed(seed)
#     np.random.seed(seed)    
#     torch.manual_seed(seed)
#     torch.cuda.manual_seed(seed)
#     torch.cuda.manual_seed_all(seed)

#     # Create train/test split using current seed
#     train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=seed)
#     print(f"Seed {seed} - Train samples: {len(train_dataset)}, Test samples: {len(test_dataset)}")

#     train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=8)
#     test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)

#     model_barcode = Predictor_barcode()
#     model_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_PSI_no_mut_5epoch_seed{seed}.pth"))
#     model_barcode.eval()
#     model_barcode = model_barcode.to(device)

#     MSELoss = nn.MSELoss()
#     optimizer = torch.optim.Adam(model_barcode.parameters(), lr=lr)

#     model_gene_barcode = Predictor_gene_barcode()
#     model_gene_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_gene_PSI_RBP_only_5epoch_seed{seed}.pth"))
#     model_gene_barcode.eval()
#     model_gene_barcode = model_gene_barcode.to(device)
    
#     predict_psi = []
#     real_psi = []
#     psi_residuals = []
#     celltypes = []
#     barcode_names = []
    
#     with torch.no_grad():
#         psi_loss = 0
#         recon_loss = 0
#         for i, (celltype, barcode_name, barcode, gx, psi) in enumerate(test_loader):
#             barcode = barcode.to(device).float()
#             barcode = barcode.permute(0, 2, 1)
#             gx = gx.to(device).float()
#             psi = psi.to(device).float()
        
#             condition = model_barcode.Barcode_model(barcode)
#             psi_pretrain = model_barcode(barcode)
        
#             psi_residual = model_gene_barcode(barcode, gx, condition)
#             psi_loss += MSELoss(psi_residual.squeeze(), psi-psi_pretrain.squeeze()).item()
            
#             predict_psi.extend(psi_residual.squeeze().cpu().numpy()+psi_pretrain.squeeze().cpu().numpy())
#             psi_residuals.extend(psi_residual.squeeze().cpu().numpy())
#             real_psi.extend(psi.cpu().numpy())
#             celltypes.extend(celltype)
#             barcode_names.extend(barcode_name)

#     pearson_correlation, _ = pearsonr(real_psi, predict_psi)
#     spearman_correlation, _ = spearmanr(real_psi, predict_psi)
#     all_correlations.append((pearson_correlation, spearman_correlation))
    
#     print(f"\nSeed {seed}:")
#     print(f"Pearson Correlation: {pearson_correlation:.4f}")
#     print(f"Spearman Correlation: {spearman_correlation:.4f}")

#     # Save predictions for this seed
#     psi_results_df = pd.DataFrame({
#         'Real_PSI': real_psi,
#         'Predicted_PSI': predict_psi,
#         'PSI_Residuals': psi_residuals,
#         'Celltype': celltypes,
#         'Barcode': barcode_names
#     })
#     psi_results_df.to_csv(os.path.join(output_dir, f'psi_predictions_barcode_gene_RBP_only_seed{seed}.csv'), index=False)
#     print(f"Saved PSI predictions to {os.path.join(output_dir, f'psi_predictions_barcode_gene_RBP_only_seed{seed}.csv')}")

#     # Create and save scatter plot for this seed
#     plt.figure(figsize=(8, 8), dpi=300)
#     plt.scatter(real_psi, predict_psi, alpha=0.5, s=5, c='#336695', edgecolors='none', marker='o', rasterized=True)
#     plt.plot([-10, 10], [-10, 10], 'k--', alpha=0.5, zorder=0)
#     plt.xlabel("Observed PSI", fontsize=14, fontweight='bold')
#     plt.ylabel("Predicted PSI", fontsize=14, fontweight='bold')
#     plt.xticks(fontsize=12)
#     plt.yticks(fontsize=12)
#     plt.xlim(min(real_psi), max(real_psi))
#     plt.ylim(min(predict_psi), max(predict_psi))
#     plt.gca().spines['right'].set_visible(False)
#     plt.gca().spines['top'].set_visible(False)
#     plt.gca().spines['left'].set_linewidth(1.5)
#     plt.gca().spines['bottom'].set_linewidth(1.5)
#     plt.title(f"Prediction Performance on Wild-type Data (Seed {seed})", fontsize=16, fontweight='bold', pad=20)
#     stats_text = f"Pearson r = {pearson_correlation:.3f}\nSpearman ρ = {spearman_correlation:.3f}"
#     plt.text(0.05, 0.95, stats_text,
#              transform=plt.gca().transAxes,
#              bbox=dict(facecolor='white', edgecolor='none', alpha=0.7),
#              fontsize=12,
#              verticalalignment='top')
#     plt.tight_layout()
#     plt.savefig(os.path.join(output_dir, f'predicted_vs_real_psi_gene_barcode_RBP_only_seed{seed}.pdf'), 
#                 bbox_inches='tight', 
#                 dpi=300)
#     plt.close()

# # After all seeds are processed, create summary statistics and plots
# pearson_values = [c[0] for c in all_correlations]
# spearman_values = [c[1] for c in all_correlations]

# # Save correlation values to CSV
# correlation_df = pd.DataFrame({
#     'Pearson': pearson_values,
#     'Spearman': spearman_values
# })
# correlation_df.to_csv(os.path.join(output_dir, 'correlation_values_model_barcode_gene_RBP_only.csv'), index=False)

# # Calculate means and stds
# pearson_mean = np.mean(pearson_values)
# pearson_std = np.std(pearson_values)
# spearman_mean = np.mean(spearman_values)
# spearman_std = np.std(spearman_values)

# # Create and save box plot
# plt.figure(figsize=(8, 6))
# box_data = [pearson_values, spearman_values]
# plt.boxplot(box_data, labels=['Pearson', 'Spearman'])
# plt.ylabel('Correlation')
# plt.title('Correlation Scores Across Seeds')
# x_positions = [1, 2]
# for i, data in enumerate([pearson_values, spearman_values]):
#     plt.scatter([x_positions[i]] * len(data), data, alpha=0.5, color='black')
# plt.gca().spines['right'].set_visible(False)
# plt.gca().spines['top'].set_visible(False)
# print(f"\nAverage across all seeds:")
# print(f"Pearson Correlation: {pearson_mean:.4f} ± {pearson_std:.4f}")
# print(f"Spearman Correlation: {spearman_mean:.4f} ± {spearman_std:.4f}")
# plt.savefig(os.path.join(output_dir, 'correlation_boxplot.pdf'), 
#             bbox_inches='tight', 
#             dpi=300)
# plt.close()

# Evaluation for model_barcode

In [39]:
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
# Loop through all 10 seeds
all_correlations_mutagenesis = []
output_dir = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/"
seed_set = range(10)
for seed in seed_set:
    random.seed(seed)
    np.random.seed(seed)    
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Create train/test split using current seed
    train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=seed)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)
    
    model_barcode = Predictor_barcode()
    model_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_PSI_no_mut_5epoch_seed{seed}.pth"))
    model_barcode.eval()
    model_barcode = model_barcode.to(device)

    predict_psi = []
    real_psi = []
    psi_residuals = []
    celltypes = []
    barcode_names = []
    with torch.no_grad():
        psi_loss = 0
        recon_loss = 0
        for i, (celltype, barcode_name, barcode, gx, psi) in enumerate(test_loader):
            barcode = barcode.to(device).float()
            barcode = barcode.permute(0, 2, 1)
            gx = gx.to(device).float()
            psi = psi.to(device).float()
        
            psi_pretrain = model_barcode(barcode)
            psi_loss += MSELoss(psi_pretrain.squeeze(), psi).item()
            
            predict_psi.extend(psi_pretrain.squeeze().cpu().numpy())
            psi_residuals.extend(psi_pretrain.squeeze().cpu().numpy())
            real_psi.extend(psi.cpu().numpy())
            celltypes.extend(celltype)
            barcode_names.extend(barcode_name)

    pearson_correlation, _ = pearsonr(real_psi, predict_psi)
    spearman_correlation, _ = spearmanr(real_psi, predict_psi)
    all_correlations_mutagenesis.append((pearson_correlation, spearman_correlation))
    
    print(f"Seed {seed}:")
    print(f"Pearson Correlation: {pearson_correlation:.4f}")
    print(f"Spearman Correlation: {spearman_correlation:.4f}")
    
    # Create scatter plot for each seed
    plt.figure(figsize=(8, 8), dpi=300)
    plt.scatter(real_psi, predict_psi, alpha=0.5, s=5, c='#336695', edgecolors='none', marker='o', rasterized=True)
    
    # Add diagonal line
    plt.plot([-10, 10], [-10, 10], 'k--', alpha=0.5, zorder=0)
    
    plt.xlabel("Observed PSI", fontsize=14, fontweight='bold')
    plt.ylabel("Predicted PSI", fontsize=14, fontweight='bold')
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    
    # Set x and y axis limits to the range of the data
    plt.xlim(-10, 10)
    plt.ylim(min(predict_psi), max(predict_psi))
    
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['left'].set_linewidth(1.5)
    plt.gca().spines['bottom'].set_linewidth(1.5)
    
    plt.title(f"Prediction Performance on Wild-type Data (Seed {seed})", fontsize=16, fontweight='bold', pad=20)
    
    # Add correlation stats in a box
    stats_text = f"Pearson r = {pearson_correlation:.3f}\nSpearman ρ = {spearman_correlation:.3f}"
    plt.text(0.05, 0.95, stats_text,
             transform=plt.gca().transAxes,
             bbox=dict(facecolor='white', edgecolor='none', alpha=0.7),
             fontsize=12,
             verticalalignment='top')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'predicted_vs_real_psi_barcode_seed{seed}.pdf'), 
                bbox_inches='tight', 
                dpi=300)
    plt.close()

    # Create a DataFrame to store the predictions and actual values for this seed
    predictions_df = pd.DataFrame({
        'Real_PSI': real_psi,
        'Predicted_PSI': predict_psi,
        'Celltype': celltypes,
        'Barcode': barcode_names
    })

    # Save predictions to CSV for this seed
    predictions_csv_path = os.path.join(output_dir, f'predictions_barcode_seed{seed}.csv')
    predictions_df.to_csv(predictions_csv_path, index=False)
    print(f"Saved predictions to {predictions_csv_path}")

# Create box plot data
pearson_values = [c[0] for c in all_correlations_mutagenesis]
spearman_values = [c[1] for c in all_correlations_mutagenesis]

# Save correlation values to CSV
correlation_df = pd.DataFrame({
    'Pearson': pearson_values,
    'Spearman': spearman_values
})
correlation_df.to_csv(os.path.join(output_dir, 'correlation_values_model_barcode.csv'), index=False)

# Calculate means and stds
pearson_mean = np.mean(pearson_values)
pearson_std = np.std(pearson_values)
spearman_mean = np.mean(spearman_values)
spearman_std = np.std(spearman_values)

# Create box plot
plt.figure(figsize=(8, 6))
box_data = [pearson_values, spearman_values]
plt.boxplot(box_data, tick_labels=['Pearson', 'Spearman'])
plt.ylabel('Correlation')
plt.title('Correlation Scores Across Seeds')

# Add individual points
x_positions = [1, 2]
for i, data in enumerate([pearson_values, spearman_values]):
    plt.scatter([x_positions[i]] * len(data), data, alpha=0.5, color='black')

plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)

print(f"\nAverage across all seeds:")
print(f"Pearson Correlation: {pearson_mean:.4f} ± {pearson_std:.4f}")
print(f"Spearman Correlation: {spearman_mean:.4f} ± {spearman_std:.4f}")

plt.savefig(os.path.join(output_dir, 'correlation_boxplot.pdf'), 
            bbox_inches='tight', 
            dpi=300)
plt.close()

Train barcodes: ['ENSG00000184156.17;KCNQ3;chr8-132134325-132134388-132132179-132132264-132137884-132138016__0:0:0'
 'ENSG00000105613.10;MAST1;chr19-12858361-12858441-12852327-12852395-12858530-12858739__0:0:0'
 'ENSG00000171109.19;MFN1;chr3-179365117-179365225-179364296-179364405-179367438-179367498__0:0:0'
 'ENSG00000203321.2;CARNMT1-AS1;chr9-74991620-74991674-74991164-74991285-74995997-74996293__0:0:0'
 'ENSG00000104823.9;ECH1;chr19-38817315-38817364-38817064-38817129-38831077-38831166__0:0:0']
Test barcodes: ['ENSG00000133106.15;EPSTI1;chr13-42963254-42963338-42953947-42954021-42969093-42969177__0:0:0'
 'ENSG00000183671.12;GPR1;chr2-206203893-206203948-206176565-206177275-206213306-206213371__0:0:0'
 'ENSG00000145741.16;BTF3;chr5-73504346-73504403-73502487-73503117-73505191-73505435__0:0:0'
 'ENSG00000124596.17;OARD1;chr6-41075266-41075349-41071595-41071675-41097712-41097787__0:0:0'
 'ENSG00000096063.16;SRPK1;chr6-35920467-35920528-35890894-35891013-35921043-35921072__0:0:0']
Train indices: 1463578, Test indices: 364700
Seed 0:
Pearson Correlation: 0.6945
Spearman Correlation: 0.7028

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed0.csv
Train barcodes: ['ENSG00000138152.10;BTBD16;chr10-122297767-122297837-122291079-122291194-122307188-122307308__0:0:0'
 'ENSG00000123411.15;IKZF4;chr12-56018125-56018177-56007668-56007734-56025053-56025158__0:0:0'
 'ENSG00000146263.12;MMS22L;chr6-97246627-97246690-97233860-97233980-97267871-97268002__0:0:0'
 'ENSG00000122126.17;OCRL;chrX-129567253-129567363-129565771-129565883-129569263-129569399__0:0:0'
 'ENSG00000137845.15;ADAM10;chr15-58643885-58643978-58640776-58640960-58646054-58646204__0:0:0']
Test barcodes: ['ENSG00000066923.18;STAG3;chr7-100182722-100182839-100182089-100182192-100189444-100189596__0:0:0'
 'ENSG00000100003.18;SEC14L2;chr22-30406341-30406385-30399642-30399718-30407094-30407154__0:0:0'
 'ENSG00000100344.11;PNPLA3;chr22-43928823-43928889-43926934-43927167-43932877-43933087__0:0:0'
 'ENSG00000183431.12;SF3A3;chr1-37978987-37979055-37976883-37976953-37979464-37979533__0:0:0'
 'ENSG00000021826.17;CPS1;chr2-210668185-210668284-210663122-210663197-210674901-210674961__0:0:0']
Train indices: 1462250, Test indices: 366028
Seed 1:
Pearson Correlation: 0.6958
Spearman Correlation: 0.7002

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed1.csv
Train barcodes: ['ENSG00000223458.2;LMO7DN-IT1;chr13-75878714-75878794-75876885-75876965-75879703-75879782__0:0:0'
 'ENSG00000164692.18;COL1A2;chr7-94409722-94409821-94409563-94409608-94410241-94410295__0:0:0'
 'ENSG00000100033.17;PRODH;chr22-18921341-18921423-18919705-18919798-18925050-18925200__0:0:0'
 'ENSG00000172995.17;ARPP21;chr3-35708968-35709070-35706973-35707082-35715438-35715476__0:0:0'
 'ENSG00000145700.10;ANKRD31;chr5-75112512-75112600-75107520-75107617-75116565-75116681__0:0:0']
Test barcodes: ['ENSG00000164134.13;NAA15;chr4-139354025-139354098-139351504-139351611-139359742-139359857__0:0:0'
 'ENSG00000136878.14;USP20;chr9-129856306-129856360-129852539-129852636-129858049-129858112__0:0:0'
 'ENSG00000177830.18;CHID1;chr11-899339-899401-893426-893519-900003-900110__0:0:0'
 'ENSG00000262879.6;RP11-156P1.3;chr17-47007839-47007884-46998699-46998817-47021581-47021721__0:0:0'
 'ENSG00000149403.13;GRIK4;chr11-120898531-120898639-120875138-120875243-120905289-120905493__0:0:0']
Train indices: 1462336, Test indices: 365942
Seed 2:
Pearson Correlation: 0.6965
Spearman Correlation: 0.7062

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed2.csv
Train barcodes: ['ENSG00000060718.22;COL11A1;chr1-102997079-102997124-102995988-102996042-102998309-102998363__0:0:0'
 'ENSG00000049541.11;RFC2;chr7-74249011-74249118-74243145-74243246-74249738-74249780__0:0:0'
 'ENSG00000155324.10;GRAMD2B;chr5-126472237-126472304-126465425-126465545-126473264-126473368__0:0:0'
 'ENSG00000166888.12;STAT6;chr12-57102828-57102921-57102289-57102496-57104725-57104813__0:0:0'
 'ENSG00000064419.14;TNPO3;chr7-128967279-128967392-128957222-128957315-128970147-128970315__0:0:0']
Test barcodes: ['ENSG00000100888.15;CHD8;chr14-21399980-21400070-21399601-21399705-21400150-21400307__0:0:0'
 'ENSG00000206503.13;HLA-A;chr6-29945233-29945281-29944499-29945091-29945450-29945870__0:0:0'
 'ENSG00000110944.9;IL23A;chr12-56339425-56339524-56338883-56339206-56339942-56340305__0:0:0'
 'ENSG00000166200.15;COPS2;chr15-49144226-49144304-49137347-49137458-49155524-49155590__0:0:0'
 'ENSG00000276409.5;CCL14;chr17-35984337-35984452-35983287-35983888-35986570-35986729__0:0:0']
Train indices: 1462613, Test indices: 365665
Seed 3:
Pearson Correlation: 0.6913
Spearman Correlation: 0.6959

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed3.csv
Train barcodes: ['ENSG00000143367.16;TUFT1;chr1-151574910-151575005-151574269-151574398-151578720-151578826__0:0:0'
 'ENSG00000104973.19;MED25;chr19-49835533-49835605-49832883-49835177-49835726-49835945__0:0:0'
 'ENSG00000084636.18;COL16A1;chr1-31683333-31683369-31683193-31683247-31683949-31684003__0:0:0'
 'ENSG00000197969.14;VPS13A;chr9-77225925-77225988-77221184-77221356-77226465-77226598__0:0:0'
 'ENSG00000260192.3;LINC02240;chr5-125440598-125440695-125325351-125325447-125498775-125498956__0:0:0']
Test barcodes: ['ENSG00000110375.3;UPK2;chr11-118951203-118951265-118925163-118925291-118956882-118957014__0:0:0'
 'ENSG00000275832.5;ARHGAP23;chr17-38490461-38490551-38490101-38490175-38491406-38491532__0:0:0'
 'ENSG00000159140.21;SON;chr21-33567156-33567267-33559586-33559775-33568970-33569087__0:0:0'
 'ENSG00000133055.9;MYBPH;chr1-203168626-203168675-203167810-203168091-203168905-203169091__0:0:0'
 'ENSG00000213064.10;SFT2D2;chr1-168236711-168236770-168235100-168235182-168239130-168239160__0:0:0']
Train indices: 1462573, Test indices: 365705
Seed 4:
Pearson Correlation: 0.6931
Spearman Correlation: 0.6936

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed4.csv
Train barcodes: ['ENSG00000106070.20;GRB10;chr7-50612740-50612839-50590062-50593098-50616209-50616347__0:0:0'
 'ENSG00000132256.20;TRIM5;chr11-5667688-5667711-5665980-5666081-5678203-5678434__0:0:0'
 'ENSG00000160633.13;SAFB;chr19-5626404-5626489-5623034-5623394-5641593-5641658__0:0:0'
 'ENSG00000123243.15;ITIH5;chr10-7609419-7609494-7585900-7586069-7615981-7616098__0:0:0'
 'ENSG00000166946.14;CCNDBP1;chr15-43185819-43185879-43185327-43185607-43189198-43189280__0:0:0']
Test barcodes: ['ENSG00000274391.5;TPTE;chr21-10577459-10577520-10570484-10570549-10578516-10578605__0:0:0'
 'ENSG00000185864.17;NPIPB4;chr16-21839104-21839140-21834581-21837744-21839249-21839310__0:0:0'
 'ENSG00000050438.17;SLC4A8;chr12-51493703-51493772-51489699-51489951-51494944-51495118__0:0:0'
 'ENSG00000143537.14;ADAM15;chr1-155052670-155052777-155051285-155051465-155053416-155053493__0:0:0'
 'ENSG00000280987.4;MATR3;chr5-139322462-139322506-139321897-139322029-139322597-139322967__0:0:0']
Train indices: 1462916, Test indices: 365362
Seed 5:
Pearson Correlation: 0.7004
Spearman Correlation: 0.7014

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed5.csv
Train barcodes: ['ENSG00000164308.17;ERAP2;chr5-96900120-96900189-96896731-96896863-96901505-96901681__0:0:0'
 'ENSG00000009335.18;UBE3C;chr7-157174918-157175034-157170303-157170450-157178689-157178847__0:0:0'
 'ENSG00000132849.21;PATJ;chr1-62017855-62017947-61990167-61990364-62037976-62038049__0:0:0'
 'ENSG00000167992.13;VWCE;chr11-61265121-61265212-61264955-61265038-61267461-61267544__0:0:0'
 'ENSG00000180071.20;ANKRD18A;chr9-38588550-38588663-38586182-38586312-38593759-38593909__0:0:0']
Test barcodes: ['ENSG00000101596.16;SMCHD1;chr18-2726451-2726524-2724898-2724995-2728456-2728596__0:0:0'
 'ENSG00000136448.13;NMT1;chr17-45096193-45096285-45086507-45086652-45098381-45098552__0:0:0'
 'ENSG00000115009.13;CCL20;chr2-227815456-227815568-227813841-227813987-227816306-227816384__0:0:0'
 'ENSG00000162946.23;DISC1;chr1-231701954-231702024-231693825-231694805-231749925-231750076__0:0:0'
 'ENSG00000168542.16;COL3A1;chr2-188989395-188989449-188988080-188988134-188990306-188990360__0:0:0']
Train indices: 1462538, Test indices: 365740
Seed 6:
Pearson Correlation: 0.7073
Spearman Correlation: 0.7101

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed6.csv
Train barcodes: ['ENSG00000156500.16;PABIR3;chrX-134847885-134847971-134847382-134847475-134849166-134849228__0:0:0'
 'ENSG00000113851.15;CRBN;chr3-3154746-3154831-3153423-3153488-3156218-3156281__0:0:0'
 'ENSG00000121578.13;B4GALT4;chr3-119218711-119218772-119216238-119216344-119224057-119224245__0:0:0'
 'ENSG00000163359.17;COL6A3;chr2-237396726-237396762-237381295-237381499-237414278-237414327__-85:0:0'
 'ENSG00000031003.10;FAM13B;chr5-137952627-137952709-137948954-137949184-137953335-137953465__0:0:0']
Test barcodes: ['ENSG00000058600.16;POLR3E;chr16-22313657-22313727-22309427-22309510-22314078-22314128__-38:0:0'
 'ENSG00000156374.16;PCGF6;chr10-103314185-103314272-103302795-103303961-103326533-103326632__0:0:0'
 'ENSG00000153363.13;LINC00467;chr1-211391615-211391697-211382735-211382925-211391826-211391976__0:0:0'
 'ENSG00000007866.22;TEAD3;chr6-35478274-35478324-35477310-35477372-35478433-35478571__0:0:0'
 'ENSG00000155115.7;GTF3C6;chr6-110960413-110960477-110959171-110959252-110962391-110962505__0:0:0']
Train indices: 1462452, Test indices: 365826
Seed 7:
Pearson Correlation: 0.6937
Spearman Correlation: 0.6955

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed7.csv
Train barcodes: ['ENSG00000134690.11;CDCA8;chr1-37706977-37707064-37703251-37703347-37708321-37709713__0:0:0'
 'ENSG00000100578.18;KIAA0586;chr14-58512521-58512627-58508554-58508709-58540070-58540136__0:0:0'
 'ENSG00000102001.13;CACNA1F;chrX-49214158-49214269-49213818-49213902-49215085-49215244__0:0:0'
 'ENSG00000167306.20;MYO5B;chr18-49990438-49990520-49980443-49980553-49992287-49992431__0:0:0'
 'ENSG00000198677.12;TTC37;chr5-95506933-95506992-95503813-95503938-95513570-95513645__-19:0:0']
Test barcodes: ['ENSG00000141030.13;COPS3;chr17-17261599-17261692-17260373-17260474-17261965-17262106__0:0:0'
 'ENSG00000065413.20;ANKRD44;chr2-197187022-197187106-197147026-197147105-197310577-197310646__0:0:0'
 'ENSG00000001617.12;SEMA3F;chr3-50174051-50174114-50173792-50173953-50174230-50174350__0:0:0'
 'ENSG00000148187.18;MRRF;chr9-122291748-122291840-122270807-122271075-122322539-122323092__0:0:0'
 'ENSG00000131966.14;ACTR10;chr14-58207935-58208018-58202854-58202927-58208998-58209107__0:0:0']
Train indices: 1462170, Test indices: 366108
Seed 8:
Pearson Correlation: 0.6945
Spearman Correlation: 0.6971

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed8.csv
Train barcodes: ['ENSG00000068971.14;PPP2R5B;chr11-64928065-64928158-64927733-64927903-64928294-64928425__0:0:0'
 'ENSG00000123240.17;OPTN;chr10-13116266-13116340-13112452-13112635-13118887-13118980__0:-57:0'
 'ENSG00000272281.6;TPTE2P2;chr13-52229325-52229431-52227004-52227096-52253744-52253833__0:0:0'
 'ENSG00000047849.22;MAP4;chr3-47867245-47867338-47857430-47857512-47869213-47869327__0:0:0'
 'ENSG00000144867.13;SRPRB;chr3-133807745-133807823-133806552-133806703-133811116-133811199__0:0:0']
Test barcodes: ['ENSG00000105879.12;CBLL1;chr7-107753894-107753978-107753410-107753511-107758142-107758571__0:0:0'
 'ENSG00000140943.17;MBTPS1;chr16-84091731-84091848-84090874-84090942-84093710-84093821__0:0:0'
 'ENSG00000129460.16;NGDN;chr14-23470905-23470977-23469743-23470101-23475170-23475308__0:0:0'
 'ENSG00000205426.10;KRT81;chr12-52288360-52288456-52287983-52288148-52289214-52289275__0:0:0'
 'ENSG00000136811.16;ODF2;chr9-128492425-128492536-128487889-128488025-128492700-128492805__0:0:0']
Train indices: 1462672, Test indices: 365606
Seed 9:
Pearson Correlation: 0.7038
Spearman Correlation: 0.7083

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed9.csv

Average across all seeds:
Pearson Correlation: 0.6971 ± 0.0049
Spearman Correlation: 0.7011 ± 0.0054

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


# Set publication-quality style
plt.rcParams.update({
    'font.family': 'Arial',
    'font.size': 12,
    'axes.linewidth': 1.5,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 12,
    'axes.titlesize': 16,
    'pdf.fonttype': 42
})
sns.set_style("ticks")

# Read correlation data
correlation_barcode_path = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/correlation_values_model_barcode.csv"
correlation_gene_barcode_path = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/correlation_values_model_barcode_gene.csv"
correlation_gene_barcode_RBP_only_path = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/correlation_values_model_barcode_gene_RBP_only.csv"
# Load the data
barcode_df = pd.read_csv(correlation_barcode_path)
gene_barcode_df = pd.read_csv(correlation_gene_barcode_path)
gene_barcode_RBP_only_df = pd.read_csv(correlation_gene_barcode_RBP_only_path)

# Create figure for comparison
fig, ax = plt.subplots(figsize=(6, 4), dpi=300)

# Create box plot data - Pearson only
box_data = [
    barcode_df['Pearson'],
    gene_barcode_RBP_only_df['Pearson'],
    gene_barcode_df['Pearson']
]

# Create box plot with custom colors
boxprops = dict(linewidth=2)
whiskerprops = dict(linewidth=2)
capprops = dict(linewidth=2)
medianprops = dict(linewidth=2, color='#444444')

bp = ax.boxplot(box_data, 
                patch_artist=True,
                boxprops=boxprops,
                whiskerprops=whiskerprops,
                capprops=capprops,
                medianprops=medianprops)

# Customize box colors
colors = ['#3498db', '#e74c3c']
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

# Add individual points with jitter
for i, data in enumerate(box_data):
    # Add jitter to x position - reduced jitter range and centered around the box position
    x = np.random.normal(0, 0.03, size=len(data)) + (i+1)
    ax.scatter(x, data, alpha=0.7, s=50, color='black', edgecolor='white', linewidth=0.5)

# Calculate and display means and stds
for i, (name, df) in enumerate([
    ('Barcode Pearson', barcode_df),
    ('Gene Barcode Pearson', gene_barcode_df),
    ('Gene Barcode RBP_only Pearson', gene_barcode_RBP_only_df)
]):
    mean = np.mean(df['Pearson'])
    std = np.std(df['Pearson'])
    print(f"{name}: {mean:.4f} ± {std:.4f}")

# Customize plot appearance
ax.set_ylabel('Pearson Correlation', fontweight='bold')
ax.set_title('Pearson Correlation Comparison', fontweight='bold')
ax.set_xticklabels(['Sequence Only', 'With RBP Expression', 'With All Gene Expression'], 
                   fontweight='bold')

# Set y-axis range from 0.5 to 0.8
ax.set_ylim(bottom=0.6, top=0.8)

# Remove top and right spines
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.spines['left'].set_linewidth(1.5)
ax.spines['bottom'].set_linewidth(1.5)

# Add grid for y-axis only
ax.yaxis.grid(True, linestyle='--', alpha=0.7)

# Adjust layout and save
plt.tight_layout()
plt.savefig(os.path.join(output_dir, 'correlation_boxplot_comparison.pdf'), bbox_inches='tight')
plt.close()

Barcode Pearson: 0.6971 ± 0.0049
Gene Barcode Pearson: 0.7302 ± 0.0063
Gene Barcode RBP_only Pearson: 0.7296 ± 0.0044

# Correlation boxplot for the finetune only with the variable sequences

In [41]:
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
# Loop through all 10 seeds
all_correlations_mutagenesis = []
output_dir = "/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/"
seed_set = range(10)
for seed in seed_set:
    random.seed(seed)
    np.random.seed(seed)    
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Create train/test split using current seed
    train_dataset, test_dataset = split_dataset_by_barcode(dataset, test_size=0.2, random_state=seed)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)
    
    model_barcode = Predictor_barcode()
    model_barcode.load_state_dict(torch.load(f"/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/model_barcode_PSI_no_mut_5epoch_seed{seed}.pth"))
    model_barcode.eval()
    model_barcode = model_barcode.to(device)

    predict_psi = []
    real_psi = []
    psi_residuals = []
    celltypes = []
    barcode_names = []
    with torch.no_grad():
        psi_loss = 0
        recon_loss = 0
        for i, (celltype, barcode_name, barcode, gx, psi) in enumerate(test_loader):
            barcode = barcode.to(device).float()
            barcode = barcode.permute(0, 2, 1)
            gx = gx.to(device).float()
            psi = psi.to(device).float()
        
            psi_pretrain = model_barcode(barcode)
            psi_loss += MSELoss(psi_pretrain.squeeze(), psi).item()
            
            predict_psi.extend(psi_pretrain.squeeze().cpu().numpy())
            psi_residuals.extend(psi_pretrain.squeeze().cpu().numpy())
            real_psi.extend(psi.cpu().numpy())
            celltypes.extend(celltype)
            barcode_names.extend(barcode_name)

    pearson_correlation, _ = pearsonr(real_psi, predict_psi)
    spearman_correlation, _ = spearmanr(real_psi, predict_psi)
    all_correlations_mutagenesis.append((pearson_correlation, spearman_correlation))
    
    print(f"Seed {seed}:")
    print(f"Pearson Correlation: {pearson_correlation:.4f}")
    print(f"Spearman Correlation: {spearman_correlation:.4f}")
    
    # Create scatter plot for each seed
    plt.figure(figsize=(8, 8), dpi=300)
    plt.scatter(real_psi, predict_psi, alpha=0.5, s=5, c='#336695', edgecolors='none', marker='o', rasterized=True)
    
    # Add diagonal line
    plt.plot([-10, 10], [-10, 10], 'k--', alpha=0.5, zorder=0)
    
    plt.xlabel("Observed PSI", fontsize=14, fontweight='bold')
    plt.ylabel("Predicted PSI", fontsize=14, fontweight='bold')
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    
    # Set x and y axis limits to the range of the data
    plt.xlim(min(real_psi), max(real_psi))
    plt.ylim(min(predict_psi), max(predict_psi))
    
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['left'].set_linewidth(1.5)
    plt.gca().spines['bottom'].set_linewidth(1.5)
    
    plt.title(f"Prediction Performance on Wild-type Data (Seed {seed})", fontsize=16, fontweight='bold', pad=20)
    
    # Add correlation stats in a box
    stats_text = f"Pearson r = {pearson_correlation:.3f}\nSpearman ρ = {spearman_correlation:.3f}"
    plt.text(0.05, 0.95, stats_text,
             transform=plt.gca().transAxes,
             bbox=dict(facecolor='white', edgecolor='none', alpha=0.7),
             fontsize=12,
             verticalalignment='top')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'predicted_vs_real_psi_barcode_with_high_var_only_seed{seed}.pdf'), 
                bbox_inches='tight', 
                dpi=300)
    plt.close()

    # Create a DataFrame to store the predictions and actual values for this seed
    predictions_df = pd.DataFrame({
        'Real_PSI': real_psi,
        'Predicted_PSI': predict_psi,
        'Celltype': celltypes,
        'Barcode': barcode_names
    })

    # Save predictions to CSV for this seed
    predictions_csv_path = os.path.join(output_dir, f'predictions_barcode_with_high_var_only_seed{seed}.csv')
    predictions_df.to_csv(predictions_csv_path, index=False)
    print(f"Saved predictions to {predictions_csv_path}")

# Create box plot data
pearson_values = [c[0] for c in all_correlations_mutagenesis]
spearman_values = [c[1] for c in all_correlations_mutagenesis]

# Save correlation values to CSV
correlation_df = pd.DataFrame({
    'Pearson': pearson_values,
    'Spearman': spearman_values
})
correlation_df.to_csv(os.path.join(output_dir, 'correlation_values_model_barcode_with_high_var_only.csv'), index=False)

# Calculate means and stds
pearson_mean = np.mean(pearson_values)
pearson_std = np.std(pearson_values)
spearman_mean = np.mean(spearman_values)
spearman_std = np.std(spearman_values)

# Create box plot
plt.figure(figsize=(8, 6))
box_data = [pearson_values, spearman_values]
plt.boxplot(box_data, tick_labels=['Pearson', 'Spearman'])
plt.ylabel('Correlation')
plt.title('Correlation Scores Across Seeds')

# Add individual points
x_positions = [1, 2]
for i, data in enumerate([pearson_values, spearman_values]):
    plt.scatter([x_positions[i]] * len(data), data, alpha=0.5, color='black')

plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)

print(f"\nAverage across all seeds:")
print(f"Pearson Correlation: {pearson_mean:.4f} ± {pearson_std:.4f}")
print(f"Spearman Correlation: {spearman_mean:.4f} ± {spearman_std:.4f}")

plt.savefig(os.path.join(output_dir, 'correlation_boxplot_with_high_var_only.pdf'), 
            bbox_inches='tight', 
            dpi=300)
plt.close()

Train barcodes: ['ENSG00000184156.17;KCNQ3;chr8-132134325-132134388-132132179-132132264-132137884-132138016__0:0:0'
 'ENSG00000105613.10;MAST1;chr19-12858361-12858441-12852327-12852395-12858530-12858739__0:0:0'
 'ENSG00000171109.19;MFN1;chr3-179365117-179365225-179364296-179364405-179367438-179367498__0:0:0'
 'ENSG00000203321.2;CARNMT1-AS1;chr9-74991620-74991674-74991164-74991285-74995997-74996293__0:0:0'
 'ENSG00000104823.9;ECH1;chr19-38817315-38817364-38817064-38817129-38831077-38831166__0:0:0']
Test barcodes: ['ENSG00000133106.15;EPSTI1;chr13-42963254-42963338-42953947-42954021-42969093-42969177__0:0:0'
 'ENSG00000183671.12;GPR1;chr2-206203893-206203948-206176565-206177275-206213306-206213371__0:0:0'
 'ENSG00000145741.16;BTF3;chr5-73504346-73504403-73502487-73503117-73505191-73505435__0:0:0'
 'ENSG00000124596.17;OARD1;chr6-41075266-41075349-41071595-41071675-41097712-41097787__0:0:0'
 'ENSG00000096063.16;SRPK1;chr6-35920467-35920528-35890894-35891013-35921043-35921072__0:0:0']
Train indices: 1463578, Test indices: 364700
Seed 0:
Pearson Correlation: 0.6945
Spearman Correlation: 0.7028
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed0.csv
Train barcodes: ['ENSG00000138152.10;BTBD16;chr10-122297767-122297837-122291079-122291194-122307188-122307308__0:0:0'
 'ENSG00000123411.15;IKZF4;chr12-56018125-56018177-56007668-56007734-56025053-56025158__0:0:0'
 'ENSG00000146263.12;MMS22L;chr6-97246627-97246690-97233860-97233980-97267871-97268002__0:0:0'
 'ENSG00000122126.17;OCRL;chrX-129567253-129567363-129565771-129565883-129569263-129569399__0:0:0'
 'ENSG00000137845.15;ADAM10;chr15-58643885-58643978-58640776-58640960-58646054-58646204__0:0:0']
Test barcodes: ['ENSG00000066923.18;STAG3;chr7-100182722-100182839-100182089-100182192-100189444-100189596__0:0:0'
 'ENSG00000100003.18;SEC14L2;chr22-30406341-30406385-30399642-30399718-30407094-30407154__0:0:0'
 'ENSG00000100344.11;PNPLA3;chr22-43928823-43928889-43926934-43927167-43932877-43933087__0:0:0'
 'ENSG00000183431.12;SF3A3;chr1-37978987-37979055-37976883-37976953-37979464-37979533__0:0:0'
 'ENSG00000021826.17;CPS1;chr2-210668185-210668284-210663122-210663197-210674901-210674961__0:0:0']
Train indices: 1462250, Test indices: 366028
Seed 1:
Pearson Correlation: 0.6958
Spearman Correlation: 0.7002
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed1.csv
Train barcodes: ['ENSG00000223458.2;LMO7DN-IT1;chr13-75878714-75878794-75876885-75876965-75879703-75879782__0:0:0'
 'ENSG00000164692.18;COL1A2;chr7-94409722-94409821-94409563-94409608-94410241-94410295__0:0:0'
 'ENSG00000100033.17;PRODH;chr22-18921341-18921423-18919705-18919798-18925050-18925200__0:0:0'
 'ENSG00000172995.17;ARPP21;chr3-35708968-35709070-35706973-35707082-35715438-35715476__0:0:0'
 'ENSG00000145700.10;ANKRD31;chr5-75112512-75112600-75107520-75107617-75116565-75116681__0:0:0']
Test barcodes: ['ENSG00000164134.13;NAA15;chr4-139354025-139354098-139351504-139351611-139359742-139359857__0:0:0'
 'ENSG00000136878.14;USP20;chr9-129856306-129856360-129852539-129852636-129858049-129858112__0:0:0'
 'ENSG00000177830.18;CHID1;chr11-899339-899401-893426-893519-900003-900110__0:0:0'
 'ENSG00000262879.6;RP11-156P1.3;chr17-47007839-47007884-46998699-46998817-47021581-47021721__0:0:0'
 'ENSG00000149403.13;GRIK4;chr11-120898531-120898639-120875138-120875243-120905289-120905493__0:0:0']
Train indices: 1462336, Test indices: 365942
Seed 2:
Pearson Correlation: 0.6965
Spearman Correlation: 0.7062
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed2.csv
Train barcodes: ['ENSG00000060718.22;COL11A1;chr1-102997079-102997124-102995988-102996042-102998309-102998363__0:0:0'
 'ENSG00000049541.11;RFC2;chr7-74249011-74249118-74243145-74243246-74249738-74249780__0:0:0'
 'ENSG00000155324.10;GRAMD2B;chr5-126472237-126472304-126465425-126465545-126473264-126473368__0:0:0'
 'ENSG00000166888.12;STAT6;chr12-57102828-57102921-57102289-57102496-57104725-57104813__0:0:0'
 'ENSG00000064419.14;TNPO3;chr7-128967279-128967392-128957222-128957315-128970147-128970315__0:0:0']
Test barcodes: ['ENSG00000100888.15;CHD8;chr14-21399980-21400070-21399601-21399705-21400150-21400307__0:0:0'
 'ENSG00000206503.13;HLA-A;chr6-29945233-29945281-29944499-29945091-29945450-29945870__0:0:0'
 'ENSG00000110944.9;IL23A;chr12-56339425-56339524-56338883-56339206-56339942-56340305__0:0:0'
 'ENSG00000166200.15;COPS2;chr15-49144226-49144304-49137347-49137458-49155524-49155590__0:0:0'
 'ENSG00000276409.5;CCL14;chr17-35984337-35984452-35983287-35983888-35986570-35986729__0:0:0']
Train indices: 1462613, Test indices: 365665
Seed 3:
Pearson Correlation: 0.6913
Spearman Correlation: 0.6959
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed3.csv
Train barcodes: ['ENSG00000143367.16;TUFT1;chr1-151574910-151575005-151574269-151574398-151578720-151578826__0:0:0'
 'ENSG00000104973.19;MED25;chr19-49835533-49835605-49832883-49835177-49835726-49835945__0:0:0'
 'ENSG00000084636.18;COL16A1;chr1-31683333-31683369-31683193-31683247-31683949-31684003__0:0:0'
 'ENSG00000197969.14;VPS13A;chr9-77225925-77225988-77221184-77221356-77226465-77226598__0:0:0'
 'ENSG00000260192.3;LINC02240;chr5-125440598-125440695-125325351-125325447-125498775-125498956__0:0:0']
Test barcodes: ['ENSG00000110375.3;UPK2;chr11-118951203-118951265-118925163-118925291-118956882-118957014__0:0:0'
 'ENSG00000275832.5;ARHGAP23;chr17-38490461-38490551-38490101-38490175-38491406-38491532__0:0:0'
 'ENSG00000159140.21;SON;chr21-33567156-33567267-33559586-33559775-33568970-33569087__0:0:0'
 'ENSG00000133055.9;MYBPH;chr1-203168626-203168675-203167810-203168091-203168905-203169091__0:0:0'
 'ENSG00000213064.10;SFT2D2;chr1-168236711-168236770-168235100-168235182-168239130-168239160__0:0:0']
Train indices: 1462573, Test indices: 365705
Seed 4:
Pearson Correlation: 0.6931
Spearman Correlation: 0.6936
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed4.csv
Train barcodes: ['ENSG00000106070.20;GRB10;chr7-50612740-50612839-50590062-50593098-50616209-50616347__0:0:0'
 'ENSG00000132256.20;TRIM5;chr11-5667688-5667711-5665980-5666081-5678203-5678434__0:0:0'
 'ENSG00000160633.13;SAFB;chr19-5626404-5626489-5623034-5623394-5641593-5641658__0:0:0'
 'ENSG00000123243.15;ITIH5;chr10-7609419-7609494-7585900-7586069-7615981-7616098__0:0:0'
 'ENSG00000166946.14;CCNDBP1;chr15-43185819-43185879-43185327-43185607-43189198-43189280__0:0:0']
Test barcodes: ['ENSG00000274391.5;TPTE;chr21-10577459-10577520-10570484-10570549-10578516-10578605__0:0:0'
 'ENSG00000185864.17;NPIPB4;chr16-21839104-21839140-21834581-21837744-21839249-21839310__0:0:0'
 'ENSG00000050438.17;SLC4A8;chr12-51493703-51493772-51489699-51489951-51494944-51495118__0:0:0'
 'ENSG00000143537.14;ADAM15;chr1-155052670-155052777-155051285-155051465-155053416-155053493__0:0:0'
 'ENSG00000280987.4;MATR3;chr5-139322462-139322506-139321897-139322029-139322597-139322967__0:0:0']
Train indices: 1462916, Test indices: 365362
Seed 5:
Pearson Correlation: 0.7004
Spearman Correlation: 0.7014
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed5.csv
Train barcodes: ['ENSG00000164308.17;ERAP2;chr5-96900120-96900189-96896731-96896863-96901505-96901681__0:0:0'
 'ENSG00000009335.18;UBE3C;chr7-157174918-157175034-157170303-157170450-157178689-157178847__0:0:0'
 'ENSG00000132849.21;PATJ;chr1-62017855-62017947-61990167-61990364-62037976-62038049__0:0:0'
 'ENSG00000167992.13;VWCE;chr11-61265121-61265212-61264955-61265038-61267461-61267544__0:0:0'
 'ENSG00000180071.20;ANKRD18A;chr9-38588550-38588663-38586182-38586312-38593759-38593909__0:0:0']
Test barcodes: ['ENSG00000101596.16;SMCHD1;chr18-2726451-2726524-2724898-2724995-2728456-2728596__0:0:0'
 'ENSG00000136448.13;NMT1;chr17-45096193-45096285-45086507-45086652-45098381-45098552__0:0:0'
 'ENSG00000115009.13;CCL20;chr2-227815456-227815568-227813841-227813987-227816306-227816384__0:0:0'
 'ENSG00000162946.23;DISC1;chr1-231701954-231702024-231693825-231694805-231749925-231750076__0:0:0'
 'ENSG00000168542.16;COL3A1;chr2-188989395-188989449-188988080-188988134-188990306-188990360__0:0:0']
Train indices: 1462538, Test indices: 365740
Seed 6:
Pearson Correlation: 0.7073
Spearman Correlation: 0.7101
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed6.csv
Train barcodes: ['ENSG00000156500.16;PABIR3;chrX-134847885-134847971-134847382-134847475-134849166-134849228__0:0:0'
 'ENSG00000113851.15;CRBN;chr3-3154746-3154831-3153423-3153488-3156218-3156281__0:0:0'
 'ENSG00000121578.13;B4GALT4;chr3-119218711-119218772-119216238-119216344-119224057-119224245__0:0:0'
 'ENSG00000163359.17;COL6A3;chr2-237396726-237396762-237381295-237381499-237414278-237414327__-85:0:0'
 'ENSG00000031003.10;FAM13B;chr5-137952627-137952709-137948954-137949184-137953335-137953465__0:0:0']
Test barcodes: ['ENSG00000058600.16;POLR3E;chr16-22313657-22313727-22309427-22309510-22314078-22314128__-38:0:0'
 'ENSG00000156374.16;PCGF6;chr10-103314185-103314272-103302795-103303961-103326533-103326632__0:0:0'
 'ENSG00000153363.13;LINC00467;chr1-211391615-211391697-211382735-211382925-211391826-211391976__0:0:0'
 'ENSG00000007866.22;TEAD3;chr6-35478274-35478324-35477310-35477372-35478433-35478571__0:0:0'
 'ENSG00000155115.7;GTF3C6;chr6-110960413-110960477-110959171-110959252-110962391-110962505__0:0:0']
Train indices: 1462452, Test indices: 365826
Seed 7:
Pearson Correlation: 0.6937
Spearman Correlation: 0.6955
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed7.csv
Train barcodes: ['ENSG00000134690.11;CDCA8;chr1-37706977-37707064-37703251-37703347-37708321-37709713__0:0:0'
 'ENSG00000100578.18;KIAA0586;chr14-58512521-58512627-58508554-58508709-58540070-58540136__0:0:0'
 'ENSG00000102001.13;CACNA1F;chrX-49214158-49214269-49213818-49213902-49215085-49215244__0:0:0'
 'ENSG00000167306.20;MYO5B;chr18-49990438-49990520-49980443-49980553-49992287-49992431__0:0:0'
 'ENSG00000198677.12;TTC37;chr5-95506933-95506992-95503813-95503938-95513570-95513645__-19:0:0']
Test barcodes: ['ENSG00000141030.13;COPS3;chr17-17261599-17261692-17260373-17260474-17261965-17262106__0:0:0'
 'ENSG00000065413.20;ANKRD44;chr2-197187022-197187106-197147026-197147105-197310577-197310646__0:0:0'
 'ENSG00000001617.12;SEMA3F;chr3-50174051-50174114-50173792-50173953-50174230-50174350__0:0:0'
 'ENSG00000148187.18;MRRF;chr9-122291748-122291840-122270807-122271075-122322539-122323092__0:0:0'
 'ENSG00000131966.14;ACTR10;chr14-58207935-58208018-58202854-58202927-58208998-58209107__0:0:0']
Train indices: 1462170, Test indices: 366108
Seed 8:
Pearson Correlation: 0.6945
Spearman Correlation: 0.6971
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed8.csv
Train barcodes: ['ENSG00000068971.14;PPP2R5B;chr11-64928065-64928158-64927733-64927903-64928294-64928425__0:0:0'
 'ENSG00000123240.17;OPTN;chr10-13116266-13116340-13112452-13112635-13118887-13118980__0:-57:0'
 'ENSG00000272281.6;TPTE2P2;chr13-52229325-52229431-52227004-52227096-52253744-52253833__0:0:0'
 'ENSG00000047849.22;MAP4;chr3-47867245-47867338-47857430-47857512-47869213-47869327__0:0:0'
 'ENSG00000144867.13;SRPRB;chr3-133807745-133807823-133806552-133806703-133811116-133811199__0:0:0']
Test barcodes: ['ENSG00000105879.12;CBLL1;chr7-107753894-107753978-107753410-107753511-107758142-107758571__0:0:0'
 'ENSG00000140943.17;MBTPS1;chr16-84091731-84091848-84090874-84090942-84093710-84093821__0:0:0'
 'ENSG00000129460.16;NGDN;chr14-23470905-23470977-23469743-23470101-23475170-23475308__0:0:0'
 'ENSG00000205426.10;KRT81;chr12-52288360-52288456-52287983-52288148-52289214-52289275__0:0:0'
 'ENSG00000136811.16;ODF2;chr9-128492425-128492536-128487889-128488025-128492700-128492805__0:0:0']
Train indices: 1462672, Test indices: 365606
Seed 9:
Pearson Correlation: 0.7038
Spearman Correlation: 0.7083
Saved predictions to /home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_with_high_var_only_seed9.csv

Average across all seeds:
Pearson Correlation: 0.6971 ± 0.0049
Spearman Correlation: 0.7011 ± 0.0054

# Now try to plot a heatmap of a few sequences across cell types.

In [42]:
from matplotlib.colors import LinearSegmentedColormap

# Read in the seed0 predictions
seed0_barcode_predictions = pd.read_csv('/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/predictions_barcode_seed0.csv')
seed0_gene_barcode_predictions = pd.read_csv('/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_seed0.csv')
seed0_gene_barcode_RBP_only_predictions = pd.read_csv('/home/dawn/lab_projects/splicing/for_kai/no_mutagenesis_data/psi_predictions_barcode_gene_RBP_only_seed0.csv')

# Convert log2(I/E) ratio back to PSI for each dataframe
for df in [seed0_barcode_predictions, seed0_gene_barcode_predictions, seed0_gene_barcode_RBP_only_predictions]:
    # Calculate I and E from log2(I/E)
    I = 1000 * (2**df['Real_PSI']) / (1 + 2**df['Real_PSI'])
    E = 1000 - I
    df['Real_PSI_converted'] = I / (I + E)
    
    # Do the same for predicted values
    I_pred = 1000 * (2**df['Predicted_PSI']) / (1 + 2**df['Predicted_PSI'])
    E_pred = 1000 - I_pred
    df['Predicted_PSI_converted'] = I_pred / (I_pred + E_pred)

# Get barcodes with at least 30 celltypes
barcodes_with_enough_celltypes = seed0_gene_barcode_predictions.groupby('Barcode').size()
barcodes_with_enough_celltypes = barcodes_with_enough_celltypes[barcodes_with_enough_celltypes >= 30].index

# Create custom colormap
colors = ["#4575B4", '#85B6D6', '#E2EFF2', '#FFE3B0', '#EF9651', '#D83629']
n_bins = 100
custom_cmap = LinearSegmentedColormap.from_list('custom_diverging', colors, N=n_bins)

def plot_heatmap(barcode_variance, title_suffix, filename_suffix):
    # Create a figure with subplots for each barcode
    fig, axes = plt.subplots(len(barcode_variance), 1, figsize=(15, 3*len(barcode_variance)))
    if len(barcode_variance) == 1:
        axes = [axes]

    for idx, (barcode, variance) in enumerate(barcode_variance.items()):
        # Get data for this barcode
        barcode_data = seed0_gene_barcode_predictions[seed0_gene_barcode_predictions['Barcode'] == barcode]
        
        # Create a 2xN matrix where N is number of cell types
        heatmap_data = np.vstack([
            barcode_data['Real_PSI'].values,
            barcode_data['Predicted_PSI'].values
        ])
        
        # Plot heatmap
        sns.heatmap(heatmap_data, 
                    ax=axes[idx],
                    cmap=custom_cmap,
                    vmin=0, 
                    vmax=1,
                    cbar_kws={'label': 'PSI'},
                    xticklabels=barcode_data['Celltype'].values,
                    yticklabels=['Real', 'Predicted'])
        
        # Add title with variance
        axes[idx].set_title(f'Barcode: {barcode}\nVariance: {variance:.4f}')
        
        # Rotate x-axis labels for better readability
        plt.setp(axes[idx].get_xticklabels(), rotation=45, ha='right')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f'barcodes_heatmap_gene_barcode_{filename_suffix}.pdf'), bbox_inches='tight')
    plt.close()

# Plot high variance barcodes
barcode_high_variance = seed0_gene_barcode_predictions[seed0_gene_barcode_predictions['Barcode'].isin(barcodes_with_enough_celltypes)].groupby(['Barcode'])['Real_PSI_converted'].var().sort_values(ascending=False).head(20)
plot_heatmap(barcode_high_variance, 'High Variance', 'high_variance')

# Plot random sample barcodes
barcode_random = seed0_gene_barcode_predictions[seed0_gene_barcode_predictions['Barcode'].isin(barcodes_with_enough_celltypes)].groupby(['Barcode'])['Real_PSI_converted'].var().sample(n=20, random_state=42)
plot_heatmap(barcode_random, 'Random Sample', 'random_sample')