In [2]:
library(tidyverse)
library(vroom)
library(data.table)
library(future)
library(future.apply)

# if pairadise is not installed, install it
if(!requireNamespace("PAIRADISE", quietly = TRUE)) {
  BiocManager::install("PAIRADISE")
}
# Also for BiocParallel
if(!requireNamespace("BiocParallel", quietly = TRUE)) {
  BiocManager::install("BiocParallel")
}
library(PAIRADISE)

reverse_complement <- function(dna_seq) {
  complement <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  nucleotides <- unlist(strsplit(dna_seq, ""))
  complement_nucleotides <- complement[nucleotides]
  reverse_complement_seq <- paste(rev(complement_nucleotides), collapse = "")
  return(reverse_complement_seq)
}

args <- commandArgs(trailingOnly = TRUE)
celltype1 <- "A375"
celltype2 <- "all"
output_filename <- args[3]

print(paste("Celltype 1: ", celltype1))
print(paste("Celltype 2: ", celltype2))
print(paste("Output filename: ", output_filename))
all_sample_reps <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_PSI_count_table.csv")
all_sample_reps <- all_sample_reps %>% 
  mutate(index_offset = paste0(index, "__", offset)) 
print("Finished reading data")

[1] "Celltype 1:  A375"
[1] "Celltype 2:  all"
[1] "Output filename:  NA"

[1] "Finished reading data"

In [3]:
all_sample_reps

        index
1       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539
2       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539
3       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539
4       ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252
5       ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252
6       ENSG00000000003.15;TSPAN6;chrX-100635177-100635252-100633930-100634029-100635557-100635746
7       ENSG00000000419.14;DPM1;chr20-50945736-50945762-50942030-50942126-50945846-50945861
8       ENSG00000000419.14;DPM1;chr20-50948628-50948662-50945736-50945923-50955185-50955285
9       ENSG00000000457.14;SCYL3;chr1-169870254-169870357-169868927-169869039-169873695-169873752
10      ENSG00000000457.14;SCYL3;chr1-169870254-169870357-169868927-169869039-169873695-169873752
11      ENSG00000000457.14;SCYL3;chr1-169873695-169873752-169870254-169870357-169875977-169876091
12      ENSG00000000457.14;SCYL3;chr1-169875977-169876091-169873695-169873752-169878633-169878819
13      ENSG00000000457.14;SCYL3;chr1-169875977-169876091-169873695-169873752-169878633-169878819
14      ENSG00000000460.17;C1orf112;chr1-169821678-169821759-169807790-169807929-169823407-169823472
15      ENSG00000000460.17;C1orf112;chr1-169821678-169821759-169807790-169807929-169823407-169823472
16      ENSG00000000460.17;C1orf112;chr1-169823407-169823472-169821678-169821759-169827050-169827199
17      ENSG00000000460.17;C1orf112;chr1-169823407-169823472-169821678-169821759-169827050-169827199
18      ENSG00000000460.17;C1orf112;chr1-169830258-169830341-169829262-169829449-169830695-169830747
19      ENSG00000000460.17;C1orf112;chr1-169843673-169843769-169842416-169842539-169847689-169847803
20      ENSG00000000460.17;C1orf112;chr1-169847689-169847803-169843673-169843769-169849499-169849604
21      ENSG00000000460.17;C1orf112;chr1-169849499-169849604-169847689-169847803-169850264-169850327
22      ENSG00000000460.17;C1orf112;chr1-169849499-169849604-169847689-169847803-169850264-169850327
23      ENSG00000000460.17;C1orf112;chr1-169850264-169850345-169849499-169849604-169851816-169851936
24      ENSG00000000938.13;FGR;chr1-27617192-27617296-27616856-27617006-27621558-27621657
25      ENSG00000001084.13;GCLC;chr6-53500431-53500513-53500199-53500350-53505391-53505496
26      ENSG00000001084.13;GCLC;chr6-53505391-53505496-53500431-53500513-53505802-53505895
27      ENSG00000001084.13;GCLC;chr6-53505802-53505895-53505391-53505496-53506912-53507025
28      ENSG00000001084.13;GCLC;chr6-53508594-53508711-53507479-53507618-53509175-53509250
29      ENSG00000001084.13;GCLC;chr6-53509175-53509250-53508594-53508711-53514203-53514337
30      ENSG00000001084.13;GCLC;chr6-53522414-53522527-53520777-53520960-53544495-53544633
⋮       ⋮
9265969 ENSG00000288686.2;XGY2;chrY-2842164-2842242-2841485-2841627-2844076-2844257
9265970 ENSG00000288690.1;FLJ43315;chr9-64031319-64031414-64026112-64026230-64054475-64054751
9265971 ENSG00000288690.1;FLJ43315;chr9-64031319-64031414-64026112-64026230-64054475-64054751
9265972 ENSG00000288692.1;RP11-621B23.1;chr4-111384668-111384697-111117149-111117272-111386135-111386234
9265973 ENSG00000288692.1;RP11-621B23.1;chr4-111384668-111384697-111117149-111117272-111386135-111386234
9265974 ENSG00000288694.1;RP11-348N17.2;chr9-64090667-64090698-64083683-64083739-64095384-64095454
9265975 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229
9265976 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229
9265977 ENSG00000288701.1;PRRC2B;chr9-131436619-131436722-131432616-131432794-131438988-131439061
9265978 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328
9265979 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328
9265980 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328
9265981 ENSG00000288701.1;PRRC2B;chr9-131483358-131483445-131482709-131482907-131484685-131484790
9265982 ENSG00000288701.1;PRRC2B;chr9-131483358-131483445-131482709-131482907-131484685-131484790
9265983 ENSG00000288701.1;PRRC2B;chr9-131484685-131484790-131483358-131483445-131484947-131485140
9265984 ENSG00000288701.1;PRRC2B;chr9-131484685-131484790-131483358-131483445-131484947-131485140
9265985 ENSG00000288701.1;PRRC2B;chr9-131486084-131486182-131484685-131484790-131487166-131487294
9265986 ENSG00000288701.1;PRRC2B;chr9-131492168-131492260-131490764-131491580-131495739-131500197
9265987 ENSG00000288710.1;RP11-386G11.12;chr12-49004963-49005018-49004506-49004633-49005119-49005165
9265988 ENSG00000288710.1;RP11-386G11.12;chr12-49004963-49005018-49004506-49004633-49005119-49005165
9265989 ENSG00000288710.1;RP11-386G11.12;chr12-49005119-49005165-49004506-49004633-49005305-49005364
9265990 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
9265991 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
9265992 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
9265993 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
9265994 ENSG00000288710.1;RP11-386G11.12;chr12-49022279-49022353-49022042-49022151-49022589-49022875
9265995 ENSG00000288717.1;RP11-852E15.4;chr3-46000912-46000955-45995957-45996035-46001083-46001283
9265996 ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389
9265997 ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389
9265998 ENSG00000288723.1;RP11-553N16.6;chr1-241742058-241742106-241728734-241728834-241765061-241765184
        mode     offset    sample       condition included_count skipped_count
1       INCLUDED 0:-69:0   769P-rep1    769P        0              0
2       INCLUDED 0:0:0     769P-rep1    769P       29              0
3       INCLUDED 15:0:0    769P-rep1    769P        0              0
4       INCLUDED 0:0:0     769P-rep1    769P       87              1
5       INCLUDED 11:0:0    769P-rep1    769P        0              1
6       INCLUDED 0:0:0     769P-rep1    769P        6              0
7       INCLUDED 0:0:0     769P-rep1    769P       16              4
8       INCLUDED 0:0:0     769P-rep1    769P        0              3
9       INCLUDED 0:-5:0    769P-rep1    769P        0              9
10      INCLUDED 0:0:0     769P-rep1    769P       92              9
11      INCLUDED 0:0:0     769P-rep1    769P       25              1
12      INCLUDED 0:-2:0    769P-rep1    769P        0              2
13      INCLUDED 0:0:0     769P-rep1    769P      107              2
14      INCLUDED -6:0:0    769P-rep1    769P        0              1
15      INCLUDED 0:0:0     769P-rep1    769P       59              1
16      INCLUDED -16:0:0   769P-rep1    769P        0             34
17      INCLUDED 0:0:0     769P-rep1    769P       18             34
18      INCLUDED 0:0:0     769P-rep1    769P        9            169
19      INCLUDED 0:0:0     769P-rep1    769P       66             21
20      INCLUDED 0:0:0     769P-rep1    769P        5             40
21      INCLUDED -15:0:0   769P-rep1    769P        0             11
22      INCLUDED 0:0:0     769P-rep1    769P       33             11
23      INCLUDED 0:0:0     769P-rep1    769P       35              1
24      INCLUDED 0:0:0     769P-rep1    769P       10              9
25      INCLUDED 0:0:0     769P-rep1    769P       24              5
26      INCLUDED 0:0:0     769P-rep1    769P       20              0
27      INCLUDED 0:0:0     769P-rep1    769P       25              5
28      INCLUDED 0:0:0     769P-rep1    769P       11             13
29      INCLUDED 0:0:0     769P-rep1    769P       19              9
30      INCLUDED 0:-102:0  769P-rep1    769P        4              6
⋮       ⋮        ⋮         ⋮            ⋮         ⋮              ⋮
9265969 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   366             0
9265970 INCLUDED 0:-7:0    VMRCRCZ-rep3 VMRCRCZ     0            91
9265971 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   280            91
9265972 INCLUDED 0:-2:0    VMRCRCZ-rep3 VMRCRCZ     0             0
9265973 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   265             0
9265974 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   147            11
9265975 INCLUDED 0:-18:0   VMRCRCZ-rep3 VMRCRCZ     2            10
9265976 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    21            10
9265977 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    15             0
9265978 INCLUDED 0:-2:0    VMRCRCZ-rep3 VMRCRCZ     3             3
9265979 INCLUDED 0:-3:0    VMRCRCZ-rep3 VMRCRCZ     0             3
9265980 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    70             3
9265981 INCLUDED 0:-5:0    VMRCRCZ-rep3 VMRCRCZ     0             8
9265982 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   138             8
9265983 INCLUDED 0:-2:0    VMRCRCZ-rep3 VMRCRCZ     0             0
9265984 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   166             0
9265985 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    46            39
9265986 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   104             0
9265987 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   106             7
9265988 INCLUDED 14:0:0    VMRCRCZ-rep3 VMRCRCZ     0             7
9265989 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    63             0
9265990 INCLUDED -49:-58:0 VMRCRCZ-rep3 VMRCRCZ     0            74
9265991 INCLUDED -49:-82:0 VMRCRCZ-rep3 VMRCRCZ     0            74
9265992 INCLUDED -49:0:0   VMRCRCZ-rep3 VMRCRCZ     4            74
9265993 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    52            74
9265994 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    70            39
9265995 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    63            16
9265996 INCLUDED 0:-2:0    VMRCRCZ-rep3 VMRCRCZ     0            34
9265997 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ   136            34
9265998 INCLUDED 0:0:0     VMRCRCZ-rep3 VMRCRCZ    34             3
        index_offset
1       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539__0:-69:0
2       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539__0:0:0
3       ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539__15:0:0
4       ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252__0:0:0
5       ENSG00000000003.15;TSPAN6;chrX-100633930-100634029-100632484-100632568-100635177-100635252__11:0:0
6       ENSG00000000003.15;TSPAN6;chrX-100635177-100635252-100633930-100634029-100635557-100635746__0:0:0
7       ENSG00000000419.14;DPM1;chr20-50945736-50945762-50942030-50942126-50945846-50945861__0:0:0
8       ENSG00000000419.14;DPM1;chr20-50948628-50948662-50945736-50945923-50955185-50955285__0:0:0
9       ENSG00000000457.14;SCYL3;chr1-169870254-169870357-169868927-169869039-169873695-169873752__0:-5:0
10      ENSG00000000457.14;SCYL3;chr1-169870254-169870357-169868927-169869039-169873695-169873752__0:0:0
11      ENSG00000000457.14;SCYL3;chr1-169873695-169873752-169870254-169870357-169875977-169876091__0:0:0
12      ENSG00000000457.14;SCYL3;chr1-169875977-169876091-169873695-169873752-169878633-169878819__0:-2:0
13      ENSG00000000457.14;SCYL3;chr1-169875977-169876091-169873695-169873752-169878633-169878819__0:0:0
14      ENSG00000000460.17;C1orf112;chr1-169821678-169821759-169807790-169807929-169823407-169823472__-6:0:0
15      ENSG00000000460.17;C1orf112;chr1-169821678-169821759-169807790-169807929-169823407-169823472__0:0:0
16      ENSG00000000460.17;C1orf112;chr1-169823407-169823472-169821678-169821759-169827050-169827199__-16:0:0
17      ENSG00000000460.17;C1orf112;chr1-169823407-169823472-169821678-169821759-169827050-169827199__0:0:0
18      ENSG00000000460.17;C1orf112;chr1-169830258-169830341-169829262-169829449-169830695-169830747__0:0:0
19      ENSG00000000460.17;C1orf112;chr1-169843673-169843769-169842416-169842539-169847689-169847803__0:0:0
20      ENSG00000000460.17;C1orf112;chr1-169847689-169847803-169843673-169843769-169849499-169849604__0:0:0
21      ENSG00000000460.17;C1orf112;chr1-169849499-169849604-169847689-169847803-169850264-169850327__-15:0:0
22      ENSG00000000460.17;C1orf112;chr1-169849499-169849604-169847689-169847803-169850264-169850327__0:0:0
23      ENSG00000000460.17;C1orf112;chr1-169850264-169850345-169849499-169849604-169851816-169851936__0:0:0
24      ENSG00000000938.13;FGR;chr1-27617192-27617296-27616856-27617006-27621558-27621657__0:0:0
25      ENSG00000001084.13;GCLC;chr6-53500431-53500513-53500199-53500350-53505391-53505496__0:0:0
26      ENSG00000001084.13;GCLC;chr6-53505391-53505496-53500431-53500513-53505802-53505895__0:0:0
27      ENSG00000001084.13;GCLC;chr6-53505802-53505895-53505391-53505496-53506912-53507025__0:0:0
28      ENSG00000001084.13;GCLC;chr6-53508594-53508711-53507479-53507618-53509175-53509250__0:0:0
29      ENSG00000001084.13;GCLC;chr6-53509175-53509250-53508594-53508711-53514203-53514337__0:0:0
30      ENSG00000001084.13;GCLC;chr6-53522414-53522527-53520777-53520960-53544495-53544633__0:-102:0
⋮       ⋮
9265969 ENSG00000288686.2;XGY2;chrY-2842164-2842242-2841485-2841627-2844076-2844257__0:0:0
9265970 ENSG00000288690.1;FLJ43315;chr9-64031319-64031414-64026112-64026230-64054475-64054751__0:-7:0
9265971 ENSG00000288690.1;FLJ43315;chr9-64031319-64031414-64026112-64026230-64054475-64054751__0:0:0
9265972 ENSG00000288692.1;RP11-621B23.1;chr4-111384668-111384697-111117149-111117272-111386135-111386234__0:-2:0
9265973 ENSG00000288692.1;RP11-621B23.1;chr4-111384668-111384697-111117149-111117272-111386135-111386234__0:0:0
9265974 ENSG00000288694.1;RP11-348N17.2;chr9-64090667-64090698-64083683-64083739-64095384-64095454__0:0:0
9265975 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229__0:-18:0
9265976 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229__0:0:0
9265977 ENSG00000288701.1;PRRC2B;chr9-131436619-131436722-131432616-131432794-131438988-131439061__0:0:0
9265978 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328__0:-2:0
9265979 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328__0:-3:0
9265980 ENSG00000288701.1;PRRC2B;chr9-131438988-131439061-131432616-131432794-131444184-131444328__0:0:0
9265981 ENSG00000288701.1;PRRC2B;chr9-131483358-131483445-131482709-131482907-131484685-131484790__0:-5:0
9265982 ENSG00000288701.1;PRRC2B;chr9-131483358-131483445-131482709-131482907-131484685-131484790__0:0:0
9265983 ENSG00000288701.1;PRRC2B;chr9-131484685-131484790-131483358-131483445-131484947-131485140__0:-2:0
9265984 ENSG00000288701.1;PRRC2B;chr9-131484685-131484790-131483358-131483445-131484947-131485140__0:0:0
9265985 ENSG00000288701.1;PRRC2B;chr9-131486084-131486182-131484685-131484790-131487166-131487294__0:0:0
9265986 ENSG00000288701.1;PRRC2B;chr9-131492168-131492260-131490764-131491580-131495739-131500197__0:0:0
9265987 ENSG00000288710.1;RP11-386G11.12;chr12-49004963-49005018-49004506-49004633-49005119-49005165__0:0:0
9265988 ENSG00000288710.1;RP11-386G11.12;chr12-49004963-49005018-49004506-49004633-49005119-49005165__14:0:0
9265989 ENSG00000288710.1;RP11-386G11.12;chr12-49005119-49005165-49004506-49004633-49005305-49005364__0:0:0
9265990 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__-49:-58:0
9265991 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__-49:-82:0
9265992 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__-49:0:0
9265993 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852__0:0:0
9265994 ENSG00000288710.1;RP11-386G11.12;chr12-49022279-49022353-49022042-49022151-49022589-49022875__0:0:0
9265995 ENSG00000288717.1;RP11-852E15.4;chr3-46000912-46000955-45995957-45996035-46001083-46001283__0:0:0
9265996 ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389__0:-2:0
9265997 ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389__0:0:0
9265998 ENSG00000288723.1;RP11-553N16.6;chr1-241742058-241742106-241728734-241728834-241765061-241765184__0:0:0

In [8]:
df <- all_sample_reps
  condition1 <- "A375"
  condition2 <- "all"
  
  # Filter data frames based on conditions
  condition1_df <- df %>% filter(condition == condition1) %>% mutate(PSI = included_count / (included_count + skipped_count))
  if (condition2 == "all") {
    condition2_df <- df %>% filter(condition != condition1) %>% mutate(PSI = included_count / (included_count + skipped_count))
  } else {
    condition2_df <- df %>% filter(condition == condition2) %>% mutate(PSI = included_count / (included_count + skipped_count))
  }
  
  condition1_df_PSI <- condition1_df %>% group_by(index_offset) %>% 
    summarise(PSI_1 = mean(PSI,na.rm=T))

  condition2_df_PSI <- condition2_df %>% group_by(index_offset) %>% 
    summarise(PSI_2 = mean(PSI, na.rm = T))

  # Merge the 2 dataframe. 
  condition1_2_merged <- merge(condition1_df_PSI, condition2_df_PSI, by = "index_offset")  %>% 
                            mutate(PSI_diff = abs(PSI_1 - PSI_2)) %>% filter(PSI_diff >= 0.1)

  # Create a list of all unique indices.
  unique_indices <- unique(condition1_2_merged$index_offset)
  
  # Function to pad vectors with zeros
  pad_with_zeros <- function(vec, target_len = 3) {
    if (length(vec) < target_len) {
      vec <- c(vec, rep(0, target_len - length(vec)))
    }
    return(vec)
  }

[1] 23964

# Cell line data with transcriptomic groups.

In [ ]:
library(tidyverse)
library(vroom)
library(data.table)
library(future)
library(future.apply)

# if pairadise is not installed, install it
if(!requireNamespace("PAIRADISE", quietly = TRUE)) {
  BiocManager::install("PAIRADISE")
}
# Also for BiocParallel
if(!requireNamespace("BiocParallel", quietly = TRUE)) {
  BiocManager::install("BiocParallel")
}
library(PAIRADISE)

reverse_complement <- function(dna_seq) {
  complement <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  nucleotides <- unlist(strsplit(dna_seq, ""))
  complement_nucleotides <- complement[nucleotides]
  reverse_complement_seq <- paste(rev(complement_nucleotides), collapse = "")
  return(reverse_complement_seq)
}

args <- commandArgs(trailingOnly = TRUE)
cluster_number <- args[1]
output_filename <- args[3]

print(paste("Celltype 1: ", celltype1))
print(paste("Celltype 2: ", celltype2))
print(paste("Output filename: ", output_filename))
all_sample_reps <- fread("/broad/dawnccle/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_PSI_count_table.csv")
all_sample_reps <- all_sample_reps %>% 
  mutate(index_offset = paste0(index, "__", offset)) 
print("Finished reading data")

transcriptomic_groups <- fread("/broad/dawnccle/melange/data/cellline_data_with_cluster.csv")


get_paradise_output <- function(df, cluster_number) {
  target_conditions <- transcriptomic_groups %>% filter(cluster == cluster_number) %>% pull(display_name)
  non_target_conditions <- transcriptomic_groups %>% filter(cluster != cluster_number) %>% pull(display_name)

  # Filter data frames based on conditions
  condition1_df <- df %>% filter(condition %in% target_conditions) %>% mutate(PSI = included_count / (included_count + skipped_count))
  condition2_df <- df %>% filter(condition %in% non_target_conditions) %>% mutate(PSI = included_count / (included_count + skipped_count))
  
  condition1_df_PSI <- condition1_df %>% group_by(index_offset) %>% 
    summarise(PSI_1 = mean(PSI,na.rm=T))

  condition2_df_PSI <- condition2_df %>% group_by(index_offset) %>% 
    summarise(PSI_2 = mean(PSI, na.rm = T))

  # Merge the 2 dataframe.
  # Also filter out the indices with PSI difference less than 0.1 so that we don't have to run calculations for them.
  condition1_2_merged <- merge(condition1_df_PSI, condition2_df_PSI, by = "index_offset")  %>% 
                            mutate(PSI_diff = abs(PSI_1 - PSI_2)) %>% filter(PSI_diff >= 0.1)

  # Create a list of all unique indices.
  unique_indices <- unique(condition1_2_merged$index_offset)
  
  # Function to pad vectors with zeros
  pad_with_zeros <- function(vec, target_len = 3) {
    if (length(vec) < target_len) {
      vec <- c(vec, rep(0, target_len - length(vec)))
    }
    return(vec)
  }
  
  
  # Create the paradise data frame using dplyr operations and future.apply for parallel processing
  paradise_df <- lapply(unique_indices, function(idx) {
    condition1_index_df <- condition1_df %>% filter(index_offset == idx) %>% arrange(sample)
    condition2_index_df <- condition2_df %>% filter(index_offset == idx) %>% arrange(sample)
    
    I1 <- pad_with_zeros(condition1_index_df$included_count)
    S1 <- pad_with_zeros(condition1_index_df$skipped_count)
    I2 <- pad_with_zeros(condition2_index_df$included_count)
    S2 <- pad_with_zeros(condition2_index_df$skipped_count)
    
    return (data.frame(
      ExonID = idx, 
      I1 = paste(I1, collapse = ","), 
      S1 = paste(S1, collapse = ","), 
      I2 = paste(I2, collapse = ","), 
      S2 = paste(S2, collapse = ","), 
      I_len = 1, 
      S_len = 1
    ))
  }) %>% bind_rows()
  
  return(paradise_df)
}

formatted_df <- get_paradise_output(all_sample_reps, cluster_number)
print("Finished formatting data")
print(output_filename)
write_tsv(formatted_df, file = output_filename)

In [21]:
transcriptomic_groups <- fread("/mnt/dawnccle2/melange/data/cellline_data_with_cluster.csv")

cluster_number <- 1

# Get the cell lines in this cluster
cell_lines <- transcriptomic_groups %>% filter(cluster == cluster_number) %>% pull(display_name)


unique(transcriptomic_groups$cluster)
# Write this to a file as a df. Only 1 column, no header.
# write_tsv(data.frame(cluster = unique(transcriptomic_groups$cluster)), file = "/mnt/dawnccle2/melange/data/transcriptomic_groups.txt", col_names = FALSE)
cell_lines

 [1]  1 39 45  2  5 18 34 23 20 49 19 28 29 22  8

[1] "697"   "SEM"   "NALM6" "KOPN8"

In [1]:
library(tidyverse)
library(vroom)
library(data.table)
library(future)
library(future.apply)

# if pairadise is not installed, install it
if(!requireNamespace("PAIRADISE", quietly = TRUE)) {
  BiocManager::install("PAIRADISE")
}
# Also for BiocParallel
if(!requireNamespace("BiocParallel", quietly = TRUE)) {
  BiocManager::install("BiocParallel")
}
library(PAIRADISE)

reverse_complement <- function(dna_seq) {
  complement <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  nucleotides <- unlist(strsplit(dna_seq, ""))
  complement_nucleotides <- complement[nucleotides]
  reverse_complement_seq <- paste(rev(complement_nucleotides), collapse = "")
  return(reverse_complement_seq)
}

args <- commandArgs(trailingOnly = TRUE)
celltype1 <- "A375"
celltype2 <- "all"
output_filename <- args[3]

print(paste("Celltype 1: ", celltype1))
print(paste("Celltype 2: ", celltype2))
print(paste("Output filename: ", output_filename))
all_sample_reps <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_raw_counts.csv")
all_sample_reps <- all_sample_reps %>% 
  filter(mode == "INCLUDED") %>% 
  mutate(index_offset = paste0(index, "__", offset)) 


all_event_pairs <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_included_all_unique_event_pairs.csv") %>% select(-index)
print("Finished reading data")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘vroom’


The following objects are masked from ‘package:readr’:

    as.col_spec, col_character, col_date, col_datetime, col_double,
    col_factor, col_guess, col_integer, col_logical, col_number,
    col_skip, col_time, cols, cols_condense, cols_only, date_names,
    date_names_lang, date_names_langs, default_locale, fwf_cols,
    fwf_empty, fwf_positions, fwf_widths, locale, output_column,
    problems, spec



Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


Loading required package: nloptr

[1] "Celltype 1:  A375"
[1] "Celltype 2:  all"
[1] "Output filename:  NA"
[1] "Finished reading data"

In [3]:
df <- all_sample_reps
all_event_pairs <- all_event_pairs %>% mutate(index_offset_major_minor = paste0(index_offset_major, "___", index_offset_minor))
condition1 <- "A375"
condition2 <- "all"

# Create a function to process samples to avoid code duplication
process_samples <- function(df, all_event_pairs, samples) {
  # Pre-filter the data frames to avoid repeated filtering in the loop
  major_indices <- all_event_pairs$index_offset_major
  minor_indices <- all_event_pairs$index_offset_minor
  valid_major_minor_pairs <- all_event_pairs$index_offset_major_minor
  
  # Get data for this samples
  sample_df <- df %>% filter(sample %in% samples)
  
  # Filter once for major and minor indices
  sample_df_major <- sample_df %>% 
    filter(index_offset %in% major_indices) %>% 
    select(-count)
  
  sample_df_minor <- sample_df %>% 
    filter(index_offset %in% minor_indices) %>% 
    select(-count, -condition)
  
  # Join and filter
  sample_df_with_counts <- sample_df_major %>% 
    left_join(sample_df_minor, by = c("index" = "index", "sample" = "sample"), relationship = "many-to-many") %>% 
    mutate(index_offset_major_minor = paste0(index_offset.x, "___", index_offset.y)) %>% 
    filter(index_offset_major_minor %in% valid_major_minor_pairs)
  
  return(sample_df_with_counts)
}

# Get unique samples for each condition
unique_samples_condition1 <- df %>% 
  filter(condition == condition1) %>% 
  pull(sample) %>% 
  unique()

if (condition2 == "all") {
  unique_samples_condition2 <- df %>% 
    filter(condition != condition1) %>% 
    pull(sample) %>% 
    unique()
} else {
  unique_samples_condition2 <- df %>% 
    filter(condition == condition2) %>% 
    pull(sample) %>% 
    unique()
}

# Process each condition using the function
condition1_df <- process_samples(df, all_event_pairs, unique_samples_condition1)
condition2_df <- process_samples(df, all_event_pairs, unique_samples_condition2)

In [18]:
condition1_df_summary <- condition1_df %>% 
  mutate(altSS_1 = count_scaled.x/(count_scaled.x + count_scaled.y)) %>% 
  group_by(index_offset_major_minor) %>% 
  summarise(altSS_1 = mean(altSS_1, na.rm = TRUE)) %>% 
  select(index_offset_major_minor, altSS_1)

condition2_df_summary <- condition2_df %>% 
    mutate(altSS_2 = (count_scaled.x)/(count_scaled.x + count_scaled.y)) %>% 
    group_by(index_offset_major_minor) %>% 
    summarise(altSS_2 = mean(altSS_2, na.rm = TRUE)) %>% 
    select(index_offset_major_minor, altSS_2)

condition1_2_merged <- merge(condition1_df_summary, condition2_df_summary, by = c("index_offset_major_minor")) %>% 
  mutate(altSS_diff = abs(altSS_1 - altSS_2)) %>%
  filter(altSS_diff >= 0.1)

In [27]:
# Create a function to process samples to avoid code duplication
process_samples <- function(df, all_event_pairs, samples) {
  # Pre-filter the data frames to avoid repeated filtering in the loop
  major_indices <- all_event_pairs$index_offset_major
  minor_indices <- all_event_pairs$index_offset_minor
  valid_major_minor_pairs <- all_event_pairs$index_offset_major_minor
  
  # Get data for this samples
  sample_df <- df %>% filter(sample %in% samples)
  
  # Filter once for major and minor indices
  sample_df_major <- sample_df %>% 
    filter(index_offset %in% major_indices) %>% 
    select(-count)
  
  sample_df_minor <- sample_df %>% 
    filter(index_offset %in% minor_indices) %>% 
    select(-count, -condition)
  
  # Join and filter
  sample_df_with_counts <- sample_df_major %>% 
    left_join(sample_df_minor, by = c("index" = "index", "sample" = "sample"), relationship = "many-to-many") %>% 
    mutate(index_offset_major_minor = paste0(index_offset.x, "___", index_offset.y)) %>% 
    filter(index_offset_major_minor %in% valid_major_minor_pairs)
  
  return(sample_df_with_counts)
}

get_paradise_output <- function(df, all_event_pairs, condition1, condition2) {
# Get unique samples for each condition
unique_samples_condition1 <- df %>% 
  filter(condition == condition1) %>% 
  pull(sample) %>% 
  unique()

if (condition2 == "all") {
  unique_samples_condition2 <- df %>% 
    filter(condition != condition1) %>% 
    pull(sample) %>% 
    unique()
} else {
  unique_samples_condition2 <- df %>% 
    filter(condition == condition2) %>% 
    pull(sample) %>% 
    unique()
}

# Process each condition using the function
condition1_df <- process_samples(df, all_event_pairs, unique_samples_condition1)
condition2_df <- process_samples(df, all_event_pairs, unique_samples_condition2)
  
condition1_df_summary <- condition1_df %>% 
  mutate(altSS_1 = count_scaled.x/(count_scaled.x + count_scaled.y)) %>% 
  group_by(index_offset_major_minor) %>% 
  summarise(altSS_1 = mean(altSS_1, na.rm = TRUE)) %>% 
  select(index_offset_major_minor, altSS_1)

condition2_df_summary <- condition2_df %>% 
    mutate(altSS_2 = (count_scaled.x)/(count_scaled.x + count_scaled.y)) %>% 
    group_by(index_offset_major_minor) %>% 
    summarise(altSS_2 = mean(altSS_2, na.rm = TRUE)) %>% 
    select(index_offset_major_minor, altSS_2)

condition1_2_merged <- merge(condition1_df_summary, condition2_df_summary, by = c("index_offset_major_minor")) %>% 
  mutate(altSS_diff = abs(altSS_1 - altSS_2)) %>%
  filter(altSS_diff >= 0.1)


  # Create a list of all unique indices.
  unique_indices <- unique(condition1_2_merged$index_offset_major_minor)
  
  # Function to pad vectors with zeros
  pad_with_zeros <- function(vec, target_len = 3) {
    if (length(vec) < target_len) {
      vec <- c(vec, rep(0, target_len - length(vec)))
    }
    return(vec)
  }
  
  
  # Create the paradise data frame using dplyr operations and future.apply for parallel processing
  paradise_df <- lapply(unique_indices, function(idx) {
    condition1_index_df <- condition1_df %>% filter(index_offset_major_minor == idx) %>% arrange(sample)
    condition2_index_df <- condition2_df %>% filter(index_offset_major_minor == idx) %>% arrange(sample)
    
    I1 <- pad_with_zeros(condition1_index_df$count_scaled.x)
    S1 <- pad_with_zeros(condition1_index_df$count_scaled.y)
    I2 <- pad_with_zeros(condition2_index_df$count_scaled.x)
    S2 <- pad_with_zeros(condition2_index_df$count_scaled.y)
    
    return (data.frame(
      ExonID = idx, 
      I1 = paste(I1, collapse = ","), 
      S1 = paste(S1, collapse = ","), 
      I2 = paste(I2, collapse = ","), 
      S2 = paste(S2, collapse = ","), 
      I_len = 1, 
      S_len = 1
    ))
  }) %>% bind_rows()
  
  return(paradise_df)
}

In [28]:
formatted_df <- get_paradise_output(all_sample_reps, all_event_pairs, celltype1, celltype2)

In [7]:
library(tidyverse)
library(vroom)
library(data.table)
library(future)
library(future.apply)

# if pairadise is not installed, install it
if (!requireNamespace("PAIRADISE", quietly = TRUE)) {
  BiocManager::install("PAIRADISE")
}
# Also for BiocParallel
if (!requireNamespace("BiocParallel", quietly = TRUE)) {
  BiocManager::install("BiocParallel")
}
library(PAIRADISE)

reverse_complement <- function(dna_seq) {
  complement <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  nucleotides <- unlist(strsplit(dna_seq, ""))
  complement_nucleotides <- complement[nucleotides]
  reverse_complement_seq <- paste(rev(complement_nucleotides), collapse = "")
  return(reverse_complement_seq)
}

args <- commandArgs(trailingOnly = TRUE)
celltype1 <- "K562WT"
celltype2 <- "K562K700E"
output_filename <- args[3]

print(paste("Celltype 1: ", celltype1))
print(paste("Celltype 2: ", celltype2))
print(paste("Output filename: ", output_filename))
all_sample_reps <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_raw_counts.csv")
all_sample_reps <- all_sample_reps %>% 
  filter(mode == "INCLUDED") %>% 
  filter(grepl("DLST", index)) %>%
  mutate(index_offset = paste0(index, "__", offset)) 


all_event_pairs <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_included_all_unique_event_pairs.csv") %>% 
  select(-index) %>% 
  mutate(index_offset_major_minor = paste0(index_offset_major, "___", index_offset_minor))
print("Finished reading data")

[1] "Celltype 1:  K562WT"
[1] "Celltype 2:  K562K700E"
[1] "Output filename:  NA"

[1] "Finished reading data"

In [9]:
# Create a function to process samples to avoid code duplication
process_samples <- function(df, all_event_pairs, samples) {
  # Pre-filter the data frames to avoid repeated filtering in the loop
  major_indices <- all_event_pairs$index_offset_major
  minor_indices <- all_event_pairs$index_offset_minor
  valid_major_minor_pairs <- all_event_pairs$index_offset_major_minor
  
  sample_df <- df %>% filter(sample %in% samples) %>% select(-count)
  unique_indices_in_sample <- unique(sample_df$index_offset)
  # Create a table of all combinations of valid_major_minor_pairs and samples
  # First, get unique samples
  unique_samples <- unique(samples)
  print("Unique samples")
  print(unique_samples)
  print("Unique major indices")
  print(length(major_indices))
  print("Unique minor indices")
  print(length(minor_indices))
  print("Unique indices in sample")
  print(length(unique_indices_in_sample))
  # Create a data frame with all combinations
  combinations_table <- expand.grid(
    index_offset = unique(unique_indices_in_sample),
    sample = unique_samples,
    stringsAsFactors = FALSE
  )
  print("Combinations table")
  print(nrow(combinations_table))

  # Merge the combinations table with the sample data
  sample_df <- merge(combinations_table, sample_df, by = c("index_offset", "sample"), all.x = TRUE)
  # Set all count_scaled to 0 if they are NA
  sample_df$count_scaled <- ifelse(is.na(sample_df$count_scaled), 0, sample_df$count_scaled)
  # Reassign index by splitting index_offset
  sample_df <- sample_df %>%
    separate(index_offset, into = c("index", "offset"), sep = "__", remove = FALSE)
  print("Sample df")
  print(nrow(sample_df))
  print(sample_df)
  sample_df_major <- sample_df %>% 
    filter(index_offset %in% major_indices)
  sample_df_minor <- sample_df %>% 
      select(-condition) %>% 
      filter(index_offset %in% minor_indices)


  # Join and filter. 
  sample_df_with_counts <- sample_df_major %>% 
    left_join(sample_df_minor, by = c("index" = "index", "sample" = "sample"), relationship = "many-to-many") %>% 
    mutate(count_scaled.x = ifelse(is.na(count_scaled.x), 0, count_scaled.x),
           count_scaled.y = ifelse(is.na(count_scaled.y), 0, count_scaled.y),
           index_offset_major_minor = paste0(index_offset.x, "___", index_offset.y)) %>% 
    filter(index_offset_major_minor %in% valid_major_minor_pairs)
  
  return(sample_df_with_counts)
}

get_paradise_output <- function(df, all_event_pairs, condition1, condition2) {
  # Get unique samples for each condition
  unique_samples_condition1 <- df %>% 
    filter(condition == condition1) %>% 
    pull(sample) %>% 
    unique()
  
  if (condition2 == "all") {
    unique_samples_condition2 <- df %>% 
      filter(condition != condition1) %>% 
      pull(sample) %>% 
      unique()
  } else {
    unique_samples_condition2 <- df %>% 
      filter(condition == condition2) %>% 
      pull(sample) %>% 
      unique()
  }
  
  # Process each condition using the function
  condition1_df <- process_samples(df, all_event_pairs, unique_samples_condition1)
  condition2_df <- process_samples(df, all_event_pairs, unique_samples_condition2)
  
  condition1_df_summary <- condition1_df %>% 
    mutate(altSS_1 = count_scaled.x/(count_scaled.x + count_scaled.y)) %>% 
    group_by(index_offset_major_minor) %>% 
    summarise(altSS_1 = mean(altSS_1, na.rm = TRUE)) %>% 
    select(index_offset_major_minor, altSS_1)
  
  condition2_df_summary <- condition2_df %>% 
    mutate(altSS_2 = (count_scaled.x)/(count_scaled.x + count_scaled.y)) %>% 
    group_by(index_offset_major_minor) %>% 
    summarise(altSS_2 = mean(altSS_2, na.rm = TRUE)) %>% 
    select(index_offset_major_minor, altSS_2)
  
  condition1_2_merged <- merge(condition1_df_summary, condition2_df_summary, by = c("index_offset_major_minor")) %>% 
    mutate(altSS_diff = abs(altSS_1 - altSS_2)) 
  
  
  # Create a list of all unique indices.
  unique_indices <- unique(condition1_2_merged$index_offset_major_minor)
  
  # Function to pad vectors with zeros
  pad_with_zeros <- function(vec, target_len = 3) {
    if (length(vec) < target_len) {
      vec <- c(vec, rep(0, target_len - length(vec)))
    }
    return(vec)
  }
  
  
  # Create the paradise data frame using dplyr operations and future.apply for parallel processing
  paradise_df <- lapply(unique_indices, function(idx) {
    condition1_index_df <- condition1_df %>% filter(index_offset_major_minor == idx) %>% arrange(sample)
    condition2_index_df <- condition2_df %>% filter(index_offset_major_minor == idx) %>% arrange(sample)
    
    I1 <- pad_with_zeros(condition1_index_df$count_scaled.x)
    S1 <- pad_with_zeros(condition1_index_df$count_scaled.y)
    I2 <- pad_with_zeros(condition2_index_df$count_scaled.x)
    S2 <- pad_with_zeros(condition2_index_df$count_scaled.y)
    
    return(data.frame(
      ExonID = idx, 
      I1 = paste(I1, collapse = ","), 
      S1 = paste(S1, collapse = ","), 
      I2 = paste(I2, collapse = ","), 
      S2 = paste(S2, collapse = ","), 
      I_len = 1, 
      S_len = 1
    ))
  }) %>% bind_rows()
  
  return(paradise_df)
}

formatted_df <- get_paradise_output(all_sample_reps, all_event_pairs, celltype1, celltype2)
formatted_df

[1] "Unique samples"
[1] "K562WT-rep1" "K562WT-rep2" "K562WT-rep3"
[1] "Unique major indices"
[1] 414785
[1] "Unique minor indices"
[1] 414785
[1] "Unique indices in sample"
[1] 8
[1] "Combinations table"
[1] 24
[1] "Sample df"
[1] 24
                                                                                   index_offset
1    ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
2    ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
3    ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
4   ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
5   ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
6   ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
7    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
8    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
9    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
10 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
11 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
12 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
13   ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
14   ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
15   ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
16   ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
17   ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
18   ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
19   ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
20   ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
21   ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
22   ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
23   ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
24   ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
                                                                                 index
1  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
2  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
3  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
4  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
5  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
6  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
7  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
8  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
9  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
10 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
11 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
12 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
13 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
14 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
15 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
16 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
17 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
18 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
19 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
20 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
21 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
22 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
23 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
24 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
    offset      sample     mode count_scaled condition
1    0:0:0 K562WT-rep1 INCLUDED          104    K562WT
2    0:0:0 K562WT-rep2 INCLUDED           72    K562WT
3    0:0:0 K562WT-rep3 INCLUDED           79    K562WT
4   -2:0:0 K562WT-rep1 INCLUDED           56    K562WT
5   -2:0:0 K562WT-rep2 INCLUDED          132    K562WT
6   -2:0:0 K562WT-rep3 INCLUDED           69    K562WT
7    0:0:0 K562WT-rep1 INCLUDED            5    K562WT
8    0:0:0 K562WT-rep2 INCLUDED            9    K562WT
9    0:0:0 K562WT-rep3 INCLUDED            2    K562WT
10 -19:0:0 K562WT-rep1     <NA>            0      <NA>
11 -19:0:0 K562WT-rep2 INCLUDED            1    K562WT
12 -19:0:0 K562WT-rep3 INCLUDED            4    K562WT
13   0:0:0 K562WT-rep1 INCLUDED          114    K562WT
14   0:0:0 K562WT-rep2 INCLUDED           94    K562WT
15   0:0:0 K562WT-rep3 INCLUDED           78    K562WT
16   0:0:0 K562WT-rep1 INCLUDED            2    K562WT
17   0:0:0 K562WT-rep2 INCLUDED            4    K562WT
18   0:0:0 K562WT-rep3     <NA>            0      <NA>
19   0:0:0 K562WT-rep1 INCLUDED            2    K562WT
20   0:0:0 K562WT-rep2 INCLUDED            1    K562WT
21   0:0:0 K562WT-rep3 INCLUDED            2    K562WT
22   0:0:0 K562WT-rep1 INCLUDED            8    K562WT
23   0:0:0 K562WT-rep2     <NA>            0      <NA>
24   0:0:0 K562WT-rep3 INCLUDED            4    K562WT
[1] "Unique samples"
[1] "K562K700E-rep1" "K562K700E-rep2" "K562K700E-rep3"
[1] "Unique major indices"
[1] 414785
[1] "Unique minor indices"
[1] 414785
[1] "Unique indices in sample"
[1] 10
[1] "Combinations table"
[1] 30
[1] "Sample df"
[1] 30
                                                                                    index_offset
1     ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
2     ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
3     ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
4  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:-11:0
5  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:-11:0
6  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:-11:0
7    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
8    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
9    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
10    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
11    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
12    ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
13  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
14  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
15  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
16    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
17    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
18    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
19    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__2:0:0
20    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__2:0:0
21    ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__2:0:0
22    ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
23    ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
24    ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
25    ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
26    ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
27    ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
28    ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
29    ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
30    ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
                                                                                 index
1  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
2  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
3  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
4  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
5  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
6  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
7  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
8  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
9  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
10 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
11 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
12 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
13 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
14 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
15 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
16 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
17 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
18 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
19 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
20 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
21 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
22 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
23 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
24 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
25 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
26 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
27 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
28 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
29 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
30 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
     offset         sample     mode count_scaled condition
1     0:0:0 K562K700E-rep1 INCLUDED           84 K562K700E
2     0:0:0 K562K700E-rep2 INCLUDED           91 K562K700E
3     0:0:0 K562K700E-rep3 INCLUDED           75 K562K700E
4  -2:-11:0 K562K700E-rep1 INCLUDED            1 K562K700E
5  -2:-11:0 K562K700E-rep2     <NA>            0      <NA>
6  -2:-11:0 K562K700E-rep3     <NA>            0      <NA>
7    -2:0:0 K562K700E-rep1 INCLUDED           84 K562K700E
8    -2:0:0 K562K700E-rep2 INCLUDED           81 K562K700E
9    -2:0:0 K562K700E-rep3 INCLUDED           37 K562K700E
10    0:0:0 K562K700E-rep1 INCLUDED            1 K562K700E
11    0:0:0 K562K700E-rep2     <NA>            0      <NA>
12    0:0:0 K562K700E-rep3     <NA>            0      <NA>
13  -19:0:0 K562K700E-rep1 INCLUDED          113 K562K700E
14  -19:0:0 K562K700E-rep2 INCLUDED          151 K562K700E
15  -19:0:0 K562K700E-rep3 INCLUDED          110 K562K700E
16    0:0:0 K562K700E-rep1 INCLUDED           33 K562K700E
17    0:0:0 K562K700E-rep2 INCLUDED           41 K562K700E
18    0:0:0 K562K700E-rep3 INCLUDED           31 K562K700E
19    2:0:0 K562K700E-rep1     <NA>            0      <NA>
20    2:0:0 K562K700E-rep2 INCLUDED            2 K562K700E
21    2:0:0 K562K700E-rep3     <NA>            0      <NA>
22    0:0:0 K562K700E-rep1 INCLUDED           13 K562K700E
23    0:0:0 K562K700E-rep2 INCLUDED            3 K562K700E
24    0:0:0 K562K700E-rep3 INCLUDED            2 K562K700E
25    0:0:0 K562K700E-rep1 INCLUDED            1 K562K700E
26    0:0:0 K562K700E-rep2     <NA>            0      <NA>
27    0:0:0 K562K700E-rep3 INCLUDED            1 K562K700E
28    0:0:0 K562K700E-rep1 INCLUDED            6 K562K700E
29    0:0:0 K562K700E-rep2 INCLUDED            4 K562K700E
30    0:0:0 K562K700E-rep3 INCLUDED            5 K562K700E

  ExonID
1 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0___ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
2 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0___ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
  I1        S1    I2       S2          I_len S_len
1 56,132,69 5,9,2 84,81,37 1,0,0       1     1
2 114,94,78 0,1,4 33,41,31 113,151,110 1     1

In [38]:
  combinations_table <- expand.grid(
    index_offset = unique(c(all_event_pairs$index_offset_major, all_event_pairs$index_offset_minor)),
    sample = unique_samples,
    stringsAsFactors = FALSE
  )
  df

function (x, df1, df2, ncp, log = FALSE)
{
    if (missing(ncp))
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x5557845d46e8>
<environment: namespace:stats>

In [26]:
formatted_df

  ExonID
1 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0___ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
2 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0___ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
  I1        S1    I2       S2          I_len S_len
1 56,132,69 5,9,2 84,0,0   1,0,0       1     1
2 94,78,0   1,4,0 33,41,31 113,151,110 1     1

In [28]:
all_sample_reps %>% 
  filter(condition %in% c("K562K700E", "K562WT")) %>% 
  filter(offset %in% c("0:0:0", "-2:0:0", "-19:0:0"))

   index
1  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
2  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
3  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
4  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
5  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
6  ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
7  ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
8  ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
9  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
10 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
11 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
12 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
13 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
14 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
15 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
16 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
17 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
18 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
19 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
20 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
21 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
22 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
23 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
24 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
25 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
26 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
27 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
28 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
29 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
30 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
31 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
32 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
33 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
34 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943
35 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
36 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147
37 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
38 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167
39 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
40 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167
41 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455
42 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190
   mode     offset  count count_scaled sample         condition
1  INCLUDED 0:0:0    84    84          K562K700E-rep1 K562K700E
2  INCLUDED -2:0:0   84    84          K562K700E-rep1 K562K700E
3  INCLUDED 0:0:0     1     1          K562K700E-rep1 K562K700E
4  INCLUDED -19:0:0 113   113          K562K700E-rep1 K562K700E
5  INCLUDED 0:0:0    33    33          K562K700E-rep1 K562K700E
6  INCLUDED 0:0:0    13    13          K562K700E-rep1 K562K700E
7  INCLUDED 0:0:0     1     1          K562K700E-rep1 K562K700E
8  INCLUDED 0:0:0     6     6          K562K700E-rep1 K562K700E
9  INCLUDED 0:0:0    91    91          K562K700E-rep2 K562K700E
10 INCLUDED -2:0:0   81    81          K562K700E-rep2 K562K700E
11 INCLUDED -19:0:0 151   151          K562K700E-rep2 K562K700E
12 INCLUDED 0:0:0    41    41          K562K700E-rep2 K562K700E
13 INCLUDED 0:0:0     3     3          K562K700E-rep2 K562K700E
14 INCLUDED 0:0:0     4     4          K562K700E-rep2 K562K700E
15 INCLUDED 0:0:0    75    75          K562K700E-rep3 K562K700E
16 INCLUDED -2:0:0   37    37          K562K700E-rep3 K562K700E
17 INCLUDED -19:0:0 110   110          K562K700E-rep3 K562K700E
18 INCLUDED 0:0:0    31    31          K562K700E-rep3 K562K700E
19 INCLUDED 0:0:0     2     2          K562K700E-rep3 K562K700E
20 INCLUDED 0:0:0     1     1          K562K700E-rep3 K562K700E
21 INCLUDED 0:0:0     5     5          K562K700E-rep3 K562K700E
22 INCLUDED 0:0:0   104   104          K562WT-rep1    K562WT
23 INCLUDED -2:0:0   56    56          K562WT-rep1    K562WT
24 INCLUDED 0:0:0     5     5          K562WT-rep1    K562WT
25 INCLUDED 0:0:0   114   114          K562WT-rep1    K562WT
26 INCLUDED 0:0:0     2     2          K562WT-rep1    K562WT
27 INCLUDED 0:0:0     2     2          K562WT-rep1    K562WT
28 INCLUDED 0:0:0     8     8          K562WT-rep1    K562WT
29 INCLUDED 0:0:0    72    72          K562WT-rep2    K562WT
30 INCLUDED -2:0:0  132   132          K562WT-rep2    K562WT
31 INCLUDED 0:0:0     9     9          K562WT-rep2    K562WT
32 INCLUDED -19:0:0   1     1          K562WT-rep2    K562WT
33 INCLUDED 0:0:0    94    94          K562WT-rep2    K562WT
34 INCLUDED 0:0:0     4     4          K562WT-rep2    K562WT
35 INCLUDED 0:0:0     1     1          K562WT-rep2    K562WT
36 INCLUDED 0:0:0    79    79          K562WT-rep3    K562WT
37 INCLUDED -2:0:0   69    69          K562WT-rep3    K562WT
38 INCLUDED 0:0:0     2     2          K562WT-rep3    K562WT
39 INCLUDED -19:0:0   4     4          K562WT-rep3    K562WT
40 INCLUDED 0:0:0    78    78          K562WT-rep3    K562WT
41 INCLUDED 0:0:0     2     2          K562WT-rep3    K562WT
42 INCLUDED 0:0:0     4     4          K562WT-rep3    K562WT
   index_offset
1  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
2  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
3  ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
4  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
5  ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
6  ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
7  ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
8  ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
9  ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
10 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
11 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
12 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
13 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
14 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
15 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
16 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
17 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
18 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
19 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
20 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
21 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
22 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
23 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
24 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
25 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
26 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
27 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
28 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0
29 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
30 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
31 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
32 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
33 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
34 ENSG00000119689.15;DLST;chr14-74891055-74891167-74889274-74889349-74892833-74892943__0:0:0
35 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
36 ENSG00000119689.15;DLST;chr14-74885585-74885634-74881902-74882016-74889094-74889147__0:0:0
37 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__-2:0:0
38 ENSG00000119689.15;DLST;chr14-74889276-74889349-74881915-74882016-74891055-74891167__0:0:0
39 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__-19:0:0
40 ENSG00000119689.15;DLST;chr14-74889896-74889952-74889274-74889349-74891055-74891167__0:0:0
41 ENSG00000119689.15;DLST;chr14-74894311-74894409-74893347-74893424-74898368-74898455__0:0:0
42 ENSG00000119689.15;DLST;chr14-74900288-74900372-74899922-74899996-74901065-74901190__0:0:0